using System.Text;
using System.Text.RegularExpressions;

namespace Godswar.Server.Domain.World.Content;

/// <summary>
/// One thing a quest asks the player to kill, and how many of them.
/// </summary>
/// <remarks>
/// <paramref name="MonsterId"/> is the client's own id from
/// Text/QuestMonster.dat, which is what the frames that drive the quest
/// window carry. The map and coordinates are the position the client
/// shows for the target, used when the name cannot be resolved.
/// <para>
/// <paramref name="Match"/> is the name the client's monster table
/// gives that id, and is only set when the quest text calls the target
/// something else - quest 528 asks for eight "Fake Treasures" while the
/// world carries them as "Juno's Box" (id 1023). A kill is credited on
/// this name when there is one, otherwise on the quest text.
/// </para>
/// </remarks>
internal readonly record struct QuestObjective(
    string Target,
    string Match,
    int Required,
    uint MonsterId,
    uint MapId,
    float X,
    float Z);

/// <summary>
/// The newbie chain's kill objectives, read from the client's own quest
/// text (Text/Quest/&lt;id&gt;.dat) and Quest.xml.
/// </summary>
/// <remarks>
/// Generated by <c>tools/gen_quest_objectives.py</c>; do not edit by
/// hand. A quest that is absent here has no objective this server can
/// verify - a plain talk quest, or one that only asks for items - and is
/// therefore handed in as soon as the player asks.
/// <para>
/// Progress is stored as up to four counters packed into the single
/// progress integer of the character's quest row, because a quest can
/// name up to three targets.
/// </para>
/// </remarks>
internal static partial class StarterQuestObjectives
{
    /// <summary>Bits one objective counter occupies.</summary>
    public const int CounterBits = 8;

    /// <summary>How many objectives one quest can track.</summary>
    public const int CounterSlots = 4;

    /// <summary>Largest count a slot can hold.</summary>
    public const int CounterMaximum = (1 << CounterBits) - 1;

    /// <summary>How close a kill has to be when the name is unknown.</summary>
    public const float MatchRadius = 40.0f;

    public static IReadOnlyDictionary<uint, QuestObjective[]> ByQuestId
        { get; } = new Dictionary<uint, QuestObjective[]>
        {
            [520u] = [new QuestObjective("Dumb Wood Men", "", 10, 1027u, 0u, 186.0f, 8.0f)],
            [521u] = [new QuestObjective("Wooden Puppets", "", 12, 1021u, 0u, 139.0f, 52.0f)],
            [523u] = [new QuestObjective("Little Snakes", "", 12, 1012u, 0u, 188.0f, 111.0f)],
            [524u] = [new QuestObjective("Snakes", "", 15, 1015u, 0u, 162.0f, 198.0f)],
            [526u] = [new QuestObjective("Little Snakes", "", 15, 1012u, 0u, 117.0f, 104.0f)],
            [527u] = [new QuestObjective("Juno's Box", "", 15, 1023u, 0u, 56.0f, 133.0f)],
            [528u] = [new QuestObjective("Addiya the Destroyer", "", 1, 1492u, 0u, 39.0f, 180.0f), new QuestObjective("Fake Treasures", "Juno's Box", 8, 1023u, 0u, 71.0f, 191.0f)],
            [531u] = [new QuestObjective("Woodland Wolves", "", 20, 1431u, 4u, 202.0f, -200.0f)],
            [532u] = [new QuestObjective("Persian Spies", "", 20, 1432u, 4u, 65.0f, -45.0f)],
            [533u] = [new QuestObjective("Peninsula Bandits", "", 15, 1433u, 4u, 163.0f, -76.0f), new QuestObjective("Bloodthirsty Blademasters", "", 15, 1434u, 4u, 163.0f, -76.0f)],
            [537u] = [new QuestObjective("Flower Pixie", "", 1, 5275u, 4u, -36.0f, -208.0f), new QuestObjective("Minotaur", "", 1, 2010u, 4u, -36.0f, -208.0f)],
            [539u] = [new QuestObjective("Suburban Scorpions", "", 20, 1435u, 4u, 9.0f, -45.0f), new QuestObjective("Gold Tipped Scorpions", "", 20, 1436u, 4u, 9.0f, -45.0f)],
            [543u] = [new QuestObjective("Vicious Fawns", "", 30, 1442u, 4u, -13.0f, 39.0f)],
            [545u] = [new QuestObjective("Fluttering Swords", "", 30, 1446u, 4u, -192.0f, 31.0f), new QuestObjective("Animated Axes", "", 30, 1445u, 4u, -110.0f, -56.0f), new QuestObjective("Wild Spears", "", 30, 1447u, 4u, -134.0f, -197.0f)],
            [547u] = [new QuestObjective("Gordon", "", 1, 1026u, 4u, -181.0f, 154.0f)],
            [549u] = [new QuestObjective("Plains Boas", "", 35, 1031u, 13u, 183.0f, -51.0f)],
            [550u] = [new QuestObjective("Huge Scorpions", "", 35, 1040u, 13u, 192.0f, -166.0f)],
            [552u] = [new QuestObjective("Toxic Scorpions", "", 40, 1042u, 13u, 26.0f, -127.0f)],
            [535u] = [new QuestObjective("Garr the Fiend", "", 1, 1439u, 4u, -16.0f, 201.0f)],
            [536u] = [new QuestObjective("Scorpion Lord Alzet", "", 1, 1437u, 4u, -64.0f, -91.0f)],
            [540u] = [new QuestObjective("Silver Mane Lions", "", 30, 1438u, 4u, 21.0f, 96.0f)],
            [541u] = [new QuestObjective("Sea Dragons", "", 25, 1440u, 4u, 120.0f, 105.0f), new QuestObjective("Young Sea Dragons", "", 25, 1441u, 4u, 120.0f, 105.0f)],
            [544u] = [new QuestObjective("Brown Dragons", "", 30, 1443u, 4u, -13.0f, 39.0f)],
            [292u] = [new QuestObjective("Sicilian Elves", "", 100, 5160u, 32u, -141.0f, -170.0f)],
            [554u] = [new QuestObjective("Huge Scorpions", "", 40, 1040u, 13u, 110.0f, -131.0f)],
            [556u] = [new QuestObjective("Irascible Evil Wizards", "", 40, 1044u, 13u, -136.0f, -52.0f)],
            [559u] = [new QuestObjective("spiders", "", 1, 1030u, 0u, 0.0f, 0.0f)],
            [560u] = [new QuestObjective("Athenian Captain Mills", "", 1, 1482u, 13u, -27.0f, 41.0f)],
            [561u] = [new QuestObjective("Evil Wizard", "", 1, 1044u, 13u, -78.0f, -162.0f)],
            [562u] = [new QuestObjective("Huge Skeleton", "", 1, 1043u, 13u, -40.0f, 160.0f)],
            [563u] = [new QuestObjective("Dark Wizards", "", 1, 1045u, 13u, -175.0f, 68.0f)],
            [564u] = [new QuestObjective("Sate Lord Kross as well as 60 Dark Wizards", "", 1, 1045u, 13u, -143.0f, 161.0f)],
            [557u] = [new QuestObjective("Boas", "", 100, 1031u, 13u, 166.0f, 105.0f)],
            [558u] = [new QuestObjective("Toxic Scorpions", "", 100, 1042u, 13u, 99.0f, 139.0f)],
            [235u] = [new QuestObjective("Plains Wolves", "", 1, 1060u, 5u, -20.0f, -168.0f)],
            [293u] = [new QuestObjective("Numb Wolves", "", 100, 5161u, 32u, -102.0f, -120.0f)],
            [70u] = [new QuestObjective("Wild Lions", "", 1, 1061u, 5u, -54.0f, -11.0f)],
            [110u] = [new QuestObjective("Forest Wizards", "", 1, 1065u, 5u, 144.0f, -97.0f)],
            [75u] = [new QuestObjective("Wizards", "", 1, 1062u, 5u, 1.0f, 1.0f)],
            [240u] = [new QuestObjective("Wolf King Astrien with a group of friends", "", 1, 1063u, 5u, 51.0f, -133.0f)],
            [118u] = [new QuestObjective("Astrien", "", 1, 1063u, 5u, 51.0f, -133.0f)],
            [80u] = [new QuestObjective("Forest Wizards", "", 1, 1065u, 5u, 144.0f, -97.0f)],
            [236u] = [new QuestObjective("Huge Frogs", "", 1, 1066u, 5u, 60.0f, 40.0f)],
            [173u] = [new QuestObjective("Forest Magicians on the Isthmus of Corinth", "", 1, 1111u, 17u, 19.0f, -196.0f)],
            [238u] = [new QuestObjective("Hero Chipa", "", 1, 9043u, 5u, -200.0f, 200.0f)],
            [239u] = [new QuestObjective("Wizard Balthazar", "", 1, 1062u, 5u, 218.0f, -147.0f)],
            [294u] = [new QuestObjective("Ruthless Puppets", "", 100, 5162u, 32u, -89.0f, 9.0f)],
            [300u] = [new QuestObjective("Forest Warriors", "", 50, 1067u, 5u, 200.0f, -40.0f)],
            [87u] = [new QuestObjective("Robber Kelins", "", 1, 1081u, 16u, 1.0f, 1.0f)],
            [119u] = [new QuestObjective("Death Servants", "", 1, 1080u, 16u, -2.0f, -163.0f)],
            [217u] = [new QuestObjective("Dark Spirit Yones", "", 1, 9061u, 16u, 40.0f, -200.0f)],
            [242u] = [new QuestObjective("Death Servants", "", 1, 1080u, 16u, -2.0f, -163.0f)],
            [566u] = [new QuestObjective("Athenian Frontline Soldier", "", 10, 1503u, 68u, -7.0f, -11.0f)],
            [571u] = [new QuestObjective("Athenian General", "", 1, 1500u, 68u, -127.0f, 150.0f)],
            [174u] = [new QuestObjective("Harpy's Underlings", "", 1, 1112u, 17u, -133.0f, -201.0f)],
            [243u] = [new QuestObjective("Robber Kelins", "", 1, 1081u, 16u, -95.0f, -138.0f)],
            [104u] = [new QuestObjective("Red Deer", "", 1, 1084u, 16u, -45.0f, -24.0f)],
            [143u] = [new QuestObjective("Skeleton Mages", "", 80, 1085u, 16u, -148.0f, 16.0f)],
            [244u] = [new QuestObjective("Amazon Warriors", "", 1, 0u, 16u, 62.0f, -5.0f)],
            [330u] = [new QuestObjective("Bloodfly Wasps", "", 1, 2001u, 14u, 149.0f, -39.0f)],
            [333u] = [new QuestObjective("Bloodfly Wasps!", "", 1, 2001u, 14u, 149.0f, -39.0f)],
            [347u] = [new QuestObjective("Spider Warriors", "", 1, 2002u, 14u, 152.0f, -188.0f)],
            [295u] = [new QuestObjective("Blaze Vipers", "", 100, 5163u, 32u, -155.0f, 21.0f)],
            [334u] = [new QuestObjective("Spider Warriors", "", 1, 2002u, 14u, 152.0f, -188.0f)],
            [245u] = [new QuestObjective("Red Deer along the Argolis Coast", "", 1, 1084u, 16u, -45.0f, -24.0f)],
            [176u] = [new QuestObjective("Bronze Lions", "", 1, 1114u, 17u, -162.0f, 37.0f)],
            [105u] = [new QuestObjective("Deigo Pirates", "", 1, 1101u, 15u, 5.0f, 42.0f)],
            [221u] = [new QuestObjective("Beast Master Leader Cassirer", "", 1, 1086u, 16u, 186.0f, 76.0f)],
            [246u] = [new QuestObjective("Skeleton Mages along the Argolis Coast", "", 1, 1020u, 16u, -148.0f, 16.0f)],
            [336u] = [new QuestObjective("Frontline Cavalries", "", 1, 2006u, 14u, 72.0f, 126.0f)],
            [100u] = [new QuestObjective("Deigo Pirates", "", 1, 1101u, 15u, 5.0f, 42.0f)],
            [296u] = [new QuestObjective("Ice Wraiths", "", 100, 5165u, 32u, -30.0f, -20.0f)],
            [338u] = [new QuestObjective("Frontline Priests", "", 1, 2009u, 14u, -163.0f, 134.0f)],
            [106u] = [new QuestObjective("Persian Missionaries from Derveni", "", 1, 1104u, 15u, 157.0f, -20.0f)],
            [122u] = [new QuestObjective("Centaur Sheikh Hailer", "", 1, 3007u, 15u, 185.0f, 62.0f)],
            [339u] = [new QuestObjective("Jungle Minotaurs", "", 1, 2010u, 14u, -110.0f, 92.0f)],
            [297u] = [new QuestObjective("Gela Guards", "", 100, 5166u, 32u, -177.0f, 159.0f)],
            [332u] = [new QuestObjective("those Jungle Minotaurs", "", 1, 2010u, 14u, -110.0f, 92.0f)],
            [340u] = [new QuestObjective("Purple Winged Demons", "", 1, 2011u, 14u, -202.0f, -16.0f)],
            [388u] = [new QuestObjective("Young Red Dragons", "", 1, 1119u, 17u, -177.0f, -82.0f)],
            [307u] = [new QuestObjective("Persian Vanguards", "", 1, 1105u, 15u, 90.0f, -156.0f)],
            [309u] = [new QuestObjective("Persian Missionaries", "", 1, 1104u, 15u, 157.0f, -20.0f)],
            [351u] = [new QuestObjective("Purple Winged Demons", "", 1, 2011u, 14u, -202.0f, -16.0f)],
            [353u] = [new QuestObjective("Abyss Demons", "", 1, 2015u, 14u, -169.0f, -49.0f)],
            [341u] = [new QuestObjective("Tree Demons", "", 1, 2007u, 14u, -176.0f, -213.0f)],
            [308u] = [new QuestObjective("Ancient Crocodiles", "", 100, 1107u, 15u, -105.0f, 114.0f)],
            [310u] = [new QuestObjective("Harpies", "", 1, 1106u, 15u, -27.0f, -76.0f)],
            [319u] = [new QuestObjective("Harpies", "", 1, 1106u, 15u, -27.0f, -76.0f)],
            [354u] = [new QuestObjective("Persian Mages", "", 1, 3036u, 8u, -1.0f, -158.0f)],
            [357u] = [new QuestObjective("Rot Hide Cooers", "", 1, 3033u, 8u, -13.0f, -84.0f)],
            [298u] = [new QuestObjective("Gela Hunters", "", 100, 5167u, 32u, -82.0f, 155.0f)],
            [358u] = [new QuestObjective("White Cooers", "", 1, 3034u, 8u, -13.0f, -84.0f)],
            [393u] = [new QuestObjective("Persian Mages", "", 1, 3036u, 8u, -1.0f, -154.0f)],
            [394u] = [new QuestObjective("Persian Bandits", "", 1, 3035u, 8u, -1.0f, -154.0f)],
            [359u] = [new QuestObjective("Flaming Hounds", "", 1, 3024u, 8u, 19.0f, -5.0f)],
            [360u] = [new QuestObjective("Persian Huntresses", "", 1, 3025u, 8u, 18.0f, 71.0f)],
            [355u] = [new QuestObjective("Persian Vanguards", "", 1, 1105u, 8u, 46.0f, 122.0f)],
            [361u] = [new QuestObjective("Persian Vanguards", "", 1, 1105u, 8u, 46.0f, 122.0f)],
            [374u] = [new QuestObjective("Persian Bandits", "", 1, 3035u, 8u, -1.0f, -158.0f)],
            [376u] = [new QuestObjective("Persian Captain", "", 1, 3038u, 8u, -70.0f, 165.0f)],
            [647u] = [new QuestObjective("Alpha Demon", "", 1, 1549u, 207u, 168.0f, -145.0f)],
            [306u] = [new QuestObjective("Gela Hunters", "", 100, 5167u, 32u, -82.0f, 155.0f)],
            [356u] = [new QuestObjective("Persian Archmages", "", 1, 3020u, 8u, -118.0f, 57.0f)],
            [362u] = [new QuestObjective("Persian Whiterobe Mages to get their wand", "", 1, 3032u, 8u, 1.0f, 1.0f)],
            [370u] = [new QuestObjective("Persian Whiterobe Mages", "", 1, 3032u, 8u, 72.0f, 107.0f)],
            [363u] = [new QuestObjective("Persian Clergies", "", 1, 3005u, 8u, 102.0f, 168.0f)],
            [364u] = [new QuestObjective("Persian Scouts", "", 1, 1095u, 8u, 182.0f, 127.0f)],
            [365u] = [new QuestObjective("Persian Soldiers", "", 1, 3022u, 8u, -18.0f, 113.0f)],
            [366u] = [new QuestObjective("Persian Bowyers", "", 1, 3023u, 8u, -14.0f, 148.0f)],
            [367u] = [new QuestObjective("Persian Archmages", "", 1, 3020u, 8u, -118.0f, 57.0f)],
            [368u] = [new QuestObjective("Persian Paladins", "", 1, 3021u, 8u, -117.0f, 53.0f)],
            [380u] = [new QuestObjective("all of the Persian Paladins", "", 1, 3021u, 8u, -117.0f, 53.0f)],
            [382u] = [new QuestObjective("Mardonius", "", 1, 3030u, 8u, -184.0f, 32.0f)],
            [574u] = [new QuestObjective("Theban Spearmen", "", 200, 1509u, 9u, 71.0f, -23.0f)],
            [576u] = [new QuestObjective("Mycenaean Maulers", "", 200, 1530u, 9u, -52.0f, 41.0f)],
            [578u] = [new QuestObjective("Mycenaean Swordsmen", "", 1, 1531u, 9u, -86.0f, 177.0f), new QuestObjective("Mycenaean Vanguard", "", 1, 1532u, 9u, -30.0f, 198.0f)],
            [627u] = [new QuestObjective("Mycenaean Spearmen", "", 100, 1529u, 9u, 71.0f, -23.0f)],
            [628u] = [new QuestObjective("Mycenaean Maulers", "", 100, 1530u, 9u, -52.0f, 41.0f)],
            [629u] = [new QuestObjective("Mycenaean Swordsmen", "", 100, 1531u, 9u, -86.0f, 177.0f)],
            [630u] = [new QuestObjective("Mycenaean Vanguard", "", 1, 1532u, 9u, -33.0f, 195.0f)],
            [642u] = [new QuestObjective("Undead Raiders", "", 300, 1539u, 9u, -90.0f, -32.0f)],
            [653u] = [new QuestObjective("guardian", "", 1, 8103u, 6u, 179.0f, -40.0f)],
            [654u] = [new QuestObjective("Plainswalker", "", 1, 1552u, 6u, -157.0f, 168.0f)],
            [655u] = [new QuestObjective("Plainswalker", "", 1, 1552u, 6u, 129.0f, -155.0f)],
            [582u] = [new QuestObjective("Ravenous Deers", "", 200, 1533u, 9u, 58.0f, 174.0f)],
            [584u] = [new QuestObjective("Centaur Bandits", "", 200, 1534u, 9u, 158.0f, 92.0f)],
            [586u] = [new QuestObjective("Icy Basilisks", "", 200, 1515u, 9u, 97.0f, 41.0f)],
            [631u] = [new QuestObjective("Centaur Bandits", "", 100, 1534u, 9u, 158.0f, 92.0f)],
            [632u] = [new QuestObjective("Amazon Raiders", "", 100, 1535u, 9u, 97.0f, 41.0f)],
            [645u] = [new QuestObjective("Gela Hunter", "", 100, 5167u, 32u, -82.0f, 155.0f)],
            [587u] = [new QuestObjective("Vagrant White Bulls", "", 200, 1536u, 9u, 184.0f, -11.0f)],
            [589u] = [new QuestObjective("Centaur Bandits", "", 100, 1534u, 9u, 158.0f, 92.0f), new QuestObjective("Amazon Raiders", "", 1, 1535u, 9u, 97.0f, 41.0f)],
            [633u] = [new QuestObjective("Vagrant White Bulls", "", 100, 1536u, 9u, 184.0f, -11.0f)],
            [591u] = [new QuestObjective("Vagrant Brown Bulls", "", 200, 1537u, 9u, 174.0f, -159.0f)],
            [593u] = [new QuestObjective("Vagrant White Bulls", "", 100, 1536u, 9u, 184.0f, -11.0f), new QuestObjective("Vagrant Brown Bulls", "", 1, 1537u, 9u, 174.0f, -159.0f)],
            [643u] = [new QuestObjective("Mycenaean Female Mages", "", 300, 1545u, 9u, -155.0f, 63.0f)],
            [597u] = [new QuestObjective("Undead Raiders", "", 200, 1539u, 9u, -90.0f, -32.0f)],
            [601u] = [new QuestObjective("Undead Halberdier", "", 200, 1540u, 9u, -65.0f, -124.0f)],
            [635u] = [new QuestObjective("Undead Halberdiers", "", 100, 1540u, 9u, -65.0f, -124.0f)],
            [604u] = [new QuestObjective("Death Mages", "", 200, 1070u, 9u, 48.0f, -114.0f)],
            [605u] = [new QuestObjective("Immortal Nolsan", "", 1, 1542u, 9u, 69.0f, -186.0f)],
            [636u] = [new QuestObjective("Death Mages", "", 100, 1070u, 9u, 48.0f, -114.0f)],
            [610u] = [new QuestObjective("Immortal Nolsan", "", 1, 1542u, 9u, 69.0f, -186.0f)],
            [637u] = [new QuestObjective("Undead Dark Mages", "", 100, 1541u, 9u, 48.0f, -114.0f)],
            [614u] = [new QuestObjective("Revived Khazras", "", 200, 1538u, 9u, -166.0f, 160.0f)],
            [615u] = [new QuestObjective("Revived Khazra", "", 200, 1538u, 9u, -166.0f, 160.0f)],
            [638u] = [new QuestObjective("Revived Khazras", "", 100, 1538u, 9u, -166.0f, 160.0f)],
            [644u] = [new QuestObjective("Scorpion Lord's Servants", "", 300, 1547u, 9u, -163.0f, -82.0f)],
            [617u] = [new QuestObjective("Lurking Mountain Scorpions", "", 200, 1543u, 9u, -109.0f, -158.0f)],
            [618u] = [new QuestObjective("Lurking Mountain Scorpions", "", 200, 1543u, 9u, -109.0f, -158.0f)],
            [620u] = [new QuestObjective("Golden Scorpion Sukur", "", 1, 1544u, 9u, -190.0f, -195.0f)],
            [639u] = [new QuestObjective("Lurking Mountain Scorpions", "", 100, 1543u, 9u, -109.0f, -158.0f)],
            [622u] = [new QuestObjective("Mycenaean Female Mages", "", 200, 1545u, 9u, -155.0f, 63.0f)],
            [623u] = [new QuestObjective("Mycenaean Royal Sorcerer!", "", 1, 1546u, 9u, -188.0f, 67.0f)],
            [640u] = [new QuestObjective("Mycenaean Female Mages", "", 1, 1545u, 9u, -155.0f, 63.0f)],
            [625u] = [new QuestObjective("Scorpion Lord's Servants", "", 200, 1547u, 9u, -163.0f, -82.0f)],
            [626u] = [new QuestObjective("Scorpion Lord Selket!", "", 1, 1548u, 9u, -183.0f, -93.0f)],
            [641u] = [new QuestObjective("Scorpion Lord's Servants", "", 100, 1547u, 9u, -163.0f, -82.0f)],
            [0u] = [new QuestObjective("Dumb Wood Men", "", 10, 1027u, 0u, 184.0f, 12.0f)],
            [2u] = [new QuestObjective("Wooden Puppets", "", 10, 1021u, 0u, 146.0f, 73.0f)],
            [3u] = [new QuestObjective("Vipers", "", 1, 1019u, 4u, 23.0f, 150.0f)],
            [4u] = [new QuestObjective("Vipers", "", 1, 1019u, 4u, 23.0f, 150.0f)],
            [5u] = [new QuestObjective("Boas", "", 1, 1031u, 13u, 188.0f, -45.0f)],
            [9u] = [new QuestObjective("Little Snakes outside the Spartan Starting Area", "", 1, 1012u, 0u, 185.0f, 112.0f)],
            [20u] = [new QuestObjective("Lions", "", 1, 1025u, 4u, -31.0f, -28.0f)],
            [48u] = [new QuestObjective("Huge Spiders", "", 1, 1030u, 13u, 84.0f, -64.0f)],
            [49u] = [new QuestObjective("Scorpions", "", 1, 1040u, 13u, 193.0f, -187.0f)],
            [51u] = [new QuestObjective("Boas", "", 1, 1031u, 13u, 1.0f, 1.0f)],
            [62u] = [new QuestObjective("Toxic Scorpions", "", 1, 1042u, 13u, 12.0f, -183.0f)],
            [154u] = [new QuestObjective("Snakes", "", 1, 1015u, 0u, 164.0f, 170.0f)],
            [181u] = [new QuestObjective("Toxic Scorpions", "", 1, 1042u, 13u, 12.0f, -183.0f)],
            [185u] = [new QuestObjective("Dumb Wood Men", "", 1, 1027u, 0u, 186.0f, -2.0f)],
            [234u] = [new QuestObjective("Evil Wizards", "", 1, 1044u, 13u, -133.0f, -55.0f)],
            [304u] = [new QuestObjective("Snakes", "", 30, 1015u, 0u, 164.0f, 170.0f)],
            [476u] = [new QuestObjective("Snakes", "", 1, 1015u, 0u, 164.0f, 170.0f)],
            [477u] = [new QuestObjective("Snakes", "", 1, 1015u, 0u, 164.0f, 170.0f)],
            [478u] = [new QuestObjective("of Empusa's Dressing Boxes", "", 1, 0u, 4u, 55.0f, -123.0f)],
            [479u] = [new QuestObjective("of Empusa's Dressing Boxes", "", 1, 0u, 4u, 55.0f, -123.0f)],
            [480u] = [new QuestObjective("Ferocious Wolves", "", 1, 1024u, 4u, -96.0f, -196.0f)],
            [481u] = [new QuestObjective("Ferocious Wolves", "", 1, 1024u, 4u, -96.0f, -196.0f)],
            [482u] = [new QuestObjective("Mountain Lions", "", 1, 1025u, 4u, -31.0f, -28.0f)],
            [483u] = [new QuestObjective("Mountain Lions", "", 1, 1025u, 4u, -31.0f, -28.0f)],
            [484u] = [new QuestObjective("Vipers", "", 1, 1019u, 4u, 23.0f, 150.0f)],
            [485u] = [new QuestObjective("Vipers", "", 1, 1019u, 4u, 23.0f, 150.0f)],
            [486u] = [new QuestObjective("Skeletons", "", 1, 1020u, 4u, 83.0f, 107.0f)],
            [487u] = [new QuestObjective("Huge Spiders", "", 1, 1030u, 13u, 84.0f, -64.0f)],
            [488u] = [new QuestObjective("Huge Spiders", "", 1, 1030u, 13u, 84.0f, -64.0f)],
            [489u] = [new QuestObjective("Huge Spiders", "", 1, 1030u, 13u, 84.0f, -64.0f)],
            [490u] = [new QuestObjective("Huge Scorpions", "", 1, 1040u, 13u, 193.0f, -187.0f)],
            [491u] = [new QuestObjective("Huge Scorpions", "", 1, 1040u, 13u, 193.0f, -187.0f)],
            [492u] = [new QuestObjective("Huge Scorpions", "", 1, 1040u, 13u, 193.0f, -187.0f)],
            [493u] = [new QuestObjective("Boas", "", 1, 1031u, 13u, 188.0f, -45.0f)],
            [494u] = [new QuestObjective("Boas", "", 1, 1031u, 13u, 188.0f, -45.0f)],
            [495u] = [new QuestObjective("Boas", "", 1, 1031u, 13u, 188.0f, -45.0f)],
            [496u] = [new QuestObjective("Toxic Scorpions", "", 1, 1042u, 13u, 12.0f, -183.0f)],
            [497u] = [new QuestObjective("Toxic Scorpions", "", 1, 1042u, 13u, 12.0f, -183.0f)],
            [498u] = [new QuestObjective("Toxic Scorpions", "", 1, 1042u, 13u, 12.0f, -183.0f)],
            [499u] = [new QuestObjective("Huge Skeletons", "", 1, 1043u, 13u, -82.0f, 126.0f)],
            [500u] = [new QuestObjective("Huge Skeletons", "", 1, 1043u, 13u, -82.0f, 126.0f)],
            [501u] = [new QuestObjective("Huge Skeletons", "", 1, 1043u, 13u, -82.0f, 126.0f)],
            [502u] = [new QuestObjective("Evil Wizards", "", 1, 1044u, 13u, -133.0f, -55.0f)],
            [503u] = [new QuestObjective("Evil Wizards", "", 1, 1044u, 13u, -133.0f, -55.0f)],
            [504u] = [new QuestObjective("Evil Wizards", "", 1, 1044u, 13u, -133.0f, -55.0f)],
            [505u] = [new QuestObjective("Dark Wizards", "", 1, 1045u, 13u, -70.0f, 7.0f)],
            [506u] = [new QuestObjective("Dark Wizards", "", 1, 1045u, 13u, -70.0f, 7.0f)],
            [507u] = [new QuestObjective("Dark Wizards", "", 1, 1045u, 13u, -70.0f, 7.0f)],
            [634u] = [new QuestObjective("Vagrant White Bulls", "", 100, 1536u, 9u, 184.0f, -11.0f)],
            [650u] = [new QuestObjective("Nemean Lion", "", 1, 1550u, 210u, 121.0f, -124.0f)],
            [1520u] = [new QuestObjective("Crispy Wood Man", "", 10, 1010u, 1u, 186.0f, 8.0f)],
            [1521u] = [new QuestObjective("Little Deer", "", 12, 1011u, 1u, 139.0f, 52.0f)],
            [1523u] = [new QuestObjective("Little Bees", "", 12, 1013u, 1u, 188.0f, 111.0f)],
            [1524u] = [new QuestObjective("Wasps", "", 15, 1014u, 1u, 162.0f, 198.0f)],
            [1526u] = [new QuestObjective("Little Bees", "", 15, 1013u, 1u, 117.0f, 104.0f)],
            [1527u] = [new QuestObjective("Little Snakes", "", 15, 1012u, 1u, 54.0f, 134.0f)],
            [1528u] = [new QuestObjective("Wilemet the Controller", "", 1, 1411u, 1u, 39.0f, 180.0f)],
            [1531u] = [new QuestObjective("Sea Snakes", "", 20, 1412u, 2u, 214.0f, -192.0f)],
            [1532u] = [new QuestObjective("Persian Infiltrators", "", 20, 1413u, 2u, 65.0f, -45.0f)],
            [1533u] = [new QuestObjective("Plumed Harpies", "", 15, 1414u, 2u, 163.0f, -76.0f), new QuestObjective("Frenzied Harpies", "", 15, 1415u, 2u, 163.0f, -76.0f)],
            [1537u] = [new QuestObjective("Flower Pixie", "", 1, 5275u, 2u, -36.0f, -208.0f), new QuestObjective("Minotaur", "", 1, 2010u, 2u, -36.0f, -208.0f)],
            [1539u] = [new QuestObjective("Great Mane Plains Lions", "", 20, 1416u, 2u, 9.0f, -45.0f), new QuestObjective("Silver Mane Plains Lions", "", 20, 1417u, 2u, 9.0f, -45.0f)],
            [1543u] = [new QuestObjective("Farm Wasps", "", 30, 1423u, 2u, -13.0f, 39.0f)],
            [1545u] = [new QuestObjective("Young Firemane Dragons", "", 30, 1428u, 2u, -192.0f, 31.0f), new QuestObjective("Young Flamescale Dragons", "", 30, 1427u, 2u, -109.0f, -92.0f), new QuestObjective("Young Jade Dragons", "", 30, 1429u, 2u, -134.0f, -197.0f)],
            [1547u] = [new QuestObjective("Kelly the Venom Queen", "", 1, 1426u, 2u, -184.0f, 160.0f)],
            [1549u] = [new QuestObjective("Boas", "", 35, 1031u, 11u, 179.0f, 121.0f)],
            [1550u] = [new QuestObjective("Vicious Wolves", "", 35, 1032u, 11u, 90.0f, 124.0f)],
            [1552u] = [new QuestObjective("Robber Lolos", "", 40, 1035u, 11u, 110.0f, -128.0f)],
            [1535u] = [new QuestObjective("Snake Queen Johnna", "", 1, 1420u, 2u, -16.0f, 201.0f)],
            [1536u] = [new QuestObjective("Lion Lord Wilyeen", "", 1, 1418u, 2u, -64.0f, -91.0f)],
            [1540u] = [new QuestObjective("Demonic Black Snakes", "", 30, 1419u, 2u, 21.0f, 96.0f)],
            [1541u] = [new QuestObjective("Suburban Sea Turtles", "", 25, 1421u, 2u, 120.0f, 105.0f), new QuestObjective("Sleepy Saltwater Turtles", "", 25, 1422u, 2u, 120.0f, 105.0f)],
            [1544u] = [new QuestObjective("Woodland Drones", "", 30, 1424u, 2u, -13.0f, 39.0f)],
            [1292u] = [new QuestObjective("Sicilian Elves", "", 100, 5160u, 32u, 136.0f, -110.0f)],
            [1554u] = [new QuestObjective("Bad Tempered Deer", "", 40, 1034u, 11u, 140.0f, -40.0f)],
            [1556u] = [new QuestObjective("Crocodiles", "", 40, 1038u, 11u, -99.0f, -163.0f)],
            [1559u] = [new QuestObjective("Lions", "", 1, 1025u, 0u, 0.0f, 0.0f)],
            [1560u] = [new QuestObjective("Spartan Captain Adron", "", 1, 1466u, 11u, 14.0f, 10.0f)],
            [1561u] = [new QuestObjective("Angry Deer", "", 60, 0u, 11u, -115.0f, -66.0f)],
            [1562u] = [new QuestObjective("Crocodiles", "", 60, 1038u, 11u, -156.0f, -109.0f)],
            [1563u] = [new QuestObjective("Vicious Wolves", "", 60, 1032u, 11u, 6.0f, 155.0f)],
            [1564u] = [new QuestObjective("Skeletal Lord Darnas as well as 60 Huge Lion", "", 1, 1025u, 11u, -184.0f, 182.0f)],
            [1557u] = [new QuestObjective("Angry Deer", "", 100, 0u, 11u, 85.0f, -63.0f)],
            [1558u] = [new QuestObjective("Frogs", "", 100, 1037u, 11u, -14.0f, -171.0f)],
            [1235u] = [new QuestObjective("Poisonous Spiders", "", 1, 1050u, 3u, 135.0f, -81.0f)],
            [1293u] = [new QuestObjective("Numb Wolves", "", 100, 5161u, 32u, 62.0f, -115.0f)],
            [1110u] = [new QuestObjective("several Dark Wizards", "", 1, 1045u, 3u, -129.0f, 45.0f)],
            [1240u] = [new QuestObjective("Boar King Tomas with a group", "", 1, 1053u, 3u, 4.0f, -130.0f)],
            [1118u] = [new QuestObjective("Boar King Tomas", "", 1, 1053u, 3u, 4.0f, -130.0f)],
            [1080u] = [new QuestObjective("Dark Wizards", "", 1, 1045u, 3u, -129.0f, 45.0f)],
            [1236u] = [new QuestObjective("Poisonous Frogs", "", 1, 1056u, 3u, 142.0f, -179.0f)],
            [1173u] = [new QuestObjective("Forest Magicians on the Isthmus of Corinth", "", 1, 1111u, 17u, 19.0f, 172.0f)],
            [1083u] = [new QuestObjective("Death Mages", "", 1, 1070u, 18u, 1.0f, 1.0f)],
            [1182u] = [new QuestObjective("Wandering Skeletons", "", 1, 1057u, 3u, -103.0f, -183.0f)],
            [1238u] = [new QuestObjective("Salose", "", 1, 8042u, 3u, -150.0f, 192.0f)],
            [1239u] = [new QuestObjective("Wizard Plotau", "", 1, 8043u, 3u, -138.0f, -16.0f)],
            [1294u] = [new QuestObjective("Ruthless Puppets", "", 100, 5162u, 32u, 74.0f, 32.0f)],
            [1300u] = [new QuestObjective("Wandering Skeletons", "", 50, 1057u, 3u, -103.0f, -183.0f)],
            [1087u] = [new QuestObjective("evil Mobs", "", 1, 1071u, 18u, 1.0f, 1.0f)],
            [1119u] = [new QuestObjective("Death Mages", "", 1, 1070u, 18u, -11.0f, 95.0f)],
            [1217u] = [new QuestObjective("Soul Holder Sameng", "", 1, 8061u, 18u, -65.0f, 100.0f)],
            [1242u] = [new QuestObjective("Death Mages", "", 1, 1070u, 18u, -11.0f, 95.0f)],
            [1566u] = [new QuestObjective("Spartan Frontline Soldier", "", 10, 1502u, 68u, -7.0f, -11.0f)],
            [1571u] = [new QuestObjective("Spartan General", "", 1, 1501u, 68u, 119.0f, -136.0f)],
            [1174u] = [new QuestObjective("Harpy's Underlings", "", 1, 1112u, 17u, 113.0f, 168.0f)],
            [1243u] = [new QuestObjective("Mobs", "", 1, 1071u, 18u, 90.0f, 133.0f)],
            [1104u] = [new QuestObjective("Skeleton Warriors along the Megara Coast", "", 1, 1020u, 18u, 71.0f, -55.0f)],
            [1143u] = [new QuestObjective("Skeleton Warlocks on the Megara Coast", "", 1, 1020u, 18u, 154.0f, -41.0f)],
            [1244u] = [new QuestObjective("Pallas Pit Vipers", "", 1, 1073u, 18u, 19.0f, 2.0f)],
            [1330u] = [new QuestObjective("Dark Witches", "", 1, 3001u, 12u, 131.0f, -189.0f)],
            [1343u] = [new QuestObjective("Dark Witches", "", 1, 3001u, 12u, 131.0f, -189.0f)],
            [1347u] = [new QuestObjective("Ghostly Warriors", "", 1, 3002u, 12u, 58.0f, -99.0f)],
            [1295u] = [new QuestObjective("Blaze Vipers", "", 100, 5163u, 32u, 163.0f, 28.0f)],
            [1245u] = [new QuestObjective("Skeleton Warriors", "", 1, 1074u, 18u, 71.0f, -55.0f)],
            [1176u] = [new QuestObjective("Bronze Lions", "", 1, 1114u, 17u, -183.0f, 58.0f)],
            [1335u] = [new QuestObjective("Flaming Boas that infest Parnitha Port", "", 1, 1031u, 12u, -126.0f, -130.0f)],
            [1221u] = [new QuestObjective("Beast Master", "", 1, 0u, 18u, 156.0f, -170.0f)],
            [1246u] = [new QuestObjective("Skeleton Warlocks", "", 1, 1075u, 18u, 154.0f, -41.0f)],
            [1336u] = [new QuestObjective("Persian Clergies", "", 1, 3005u, 12u, 64.0f, 17.0f)],
            [1100u] = [new QuestObjective("Illyria Brigands", "", 1, 1091u, 19u, 0.0f, -82.0f)],
            [1296u] = [new QuestObjective("Ice Wraiths", "", 100, 5165u, 32u, 206.0f, -21.0f)],
            [1122u] = [new QuestObjective("Giant Alcyoneus", "", 1, 1093u, 19u, 195.0f, 10.0f)],
            [1297u] = [new QuestObjective("Gela Guards", "", 100, 5166u, 32u, 143.0f, 141.0f)],
            [1332u] = [new QuestObjective("those Venomous Icy Frogs around Parnitha Port", "", 1, 1037u, 12u, -30.0f, 104.0f)],
            [1388u] = [new QuestObjective("Young RedDragons", "", 1, 1119u, 17u, -161.0f, -49.0f)],
            [1351u] = [new QuestObjective("Venomsting Scorpions", "", 1, 3010u, 12u, -158.0f, 44.0f)],
            [1353u] = [new QuestObjective("Rage Flamefrogs", "", 1, 3015u, 12u, -106.0f, 160.0f)],
            [1341u] = [new QuestObjective("Mudskippers", "", 1, 3011u, 12u, 137.0f, 176.0f)],
            [1386u] = [new QuestObjective("Milier Guardsmen", "", 1, 1117u, 17u, 188.0f, -43.0f)],
            [1354u] = [new QuestObjective("Persian Bandits", "", 1, 3035u, 8u, 87.0f, -111.0f)],
            [1357u] = [new QuestObjective("Rot Hide Cooers", "", 1, 3033u, 8u, 166.0f, -41.0f)],
            [1387u] = [new QuestObjective("Skeleton Mage of Argolis", "", 1, 1020u, 16u, -148.0f, 16.0f)],
            [1298u] = [new QuestObjective("Gela Hunters", "", 100, 5167u, 32u, 102.0f, 138.0f)],
            [1358u] = [new QuestObjective("White Cooers", "", 1, 3034u, 8u, 166.0f, -41.0f)],
            [1393u] = [new QuestObjective("Persian Mages", "", 1, 3036u, 8u, 68.0f, -149.0f)],
            [1394u] = [new QuestObjective("Persian Bandits", "", 1, 3035u, 8u, 68.0f, -149.0f)],
            [1359u] = [new QuestObjective("Flaming Hound", "", 1, 3024u, 8u, 19.0f, -5.0f)],
            [1360u] = [new QuestObjective("Persian Huntresses", "", 1, 3025u, 8u, 18.0f, 71.0f)],
            [1355u] = [new QuestObjective("Persian Vanguards", "", 1, 1105u, 8u, 46.0f, 122.0f)],
            [1361u] = [new QuestObjective("Persian Vanguards", "", 1, 1105u, 8u, 46.0f, 122.0f)],
            [1374u] = [new QuestObjective("Persian Bandits", "", 1, 3035u, 8u, 87.0f, -111.0f)],
            [1376u] = [new QuestObjective("Persian Captain", "", 1, 3038u, 8u, -70.0f, 165.0f)],
            [1647u] = [new QuestObjective("Alpha Demon", "", 1, 1549u, 207u, 168.0f, -145.0f)],
            [1306u] = [new QuestObjective("Gela Hunters", "", 100, 5167u, 32u, 102.0f, 138.0f)],
            [1356u] = [new QuestObjective("Persian Paladins", "", 1, 3021u, 8u, -117.0f, 53.0f)],
            [1362u] = [new QuestObjective("Persian Whiterobe Mages", "", 1, 3032u, 8u, 1.0f, 1.0f)],
            [1363u] = [new QuestObjective("Persian Clergies", "", 1, 3005u, 8u, 102.0f, 168.0f)],
            [1364u] = [new QuestObjective("Persian Hammer Warriors", "", 1, 3027u, 8u, 182.0f, 127.0f)],
            [1365u] = [new QuestObjective("Persian Soldiers", "", 1, 3022u, 8u, -18.0f, 113.0f)],
            [1366u] = [new QuestObjective("Persian Bowyers", "", 1, 3023u, 8u, -14.0f, 148.0f)],
            [1367u] = [new QuestObjective("Persian Archmages", "", 1, 3020u, 8u, -118.0f, 57.0f)],
            [1368u] = [new QuestObjective("Persian Paladins", "", 1, 3021u, 8u, -117.0f, 53.0f)],
            [1380u] = [new QuestObjective("all the Persian Paladins", "", 1, 3021u, 8u, -117.0f, 53.0f)],
            [1382u] = [new QuestObjective("Mardonius", "", 1, 3030u, 8u, -184.0f, 32.0f)],
            [1574u] = [new QuestObjective("Mycenaean Spearmen", "", 200, 1529u, 9u, 71.0f, -23.0f)],
            [1576u] = [new QuestObjective("Mycenaean Maulers", "", 200, 1530u, 9u, -52.0f, 41.0f)],
            [1578u] = [new QuestObjective("Mycenaean Swordsmen", "", 1, 1531u, 9u, -86.0f, 177.0f), new QuestObjective("Mycenaean Vanguard", "", 1, 1532u, 9u, -30.0f, 198.0f)],
            [1627u] = [new QuestObjective("Mycenaean Spearmen", "", 100, 1529u, 9u, 71.0f, -23.0f)],
            [1628u] = [new QuestObjective("Mycenaean Maulers", "", 100, 1530u, 9u, -52.0f, 41.0f)],
            [1629u] = [new QuestObjective("Mycenaean Swordsmen", "", 100, 1531u, 9u, -86.0f, 177.0f)],
            [1630u] = [new QuestObjective("Mycenaean Vanguard", "", 1, 1532u, 9u, -33.0f, 195.0f)],
            [1642u] = [new QuestObjective("Undead Raiders", "", 300, 1539u, 9u, -90.0f, -32.0f)],
            [1653u] = [new QuestObjective("guardian", "", 1, 8103u, 6u, 179.0f, -40.0f)],
            [1654u] = [new QuestObjective("Plainswalker", "", 1, 1552u, 6u, -157.0f, 168.0f)],
            [1655u] = [new QuestObjective("Plainswalker", "", 1, 1552u, 6u, 129.0f, -155.0f)],
            [1582u] = [new QuestObjective("Ravenous Deer", "", 200, 1533u, 9u, 58.0f, 174.0f)],
            [1584u] = [new QuestObjective("Centaur Bandits", "", 200, 1534u, 9u, 158.0f, 92.0f)],
            [1586u] = [new QuestObjective("Amazon Raiders", "", 200, 1535u, 9u, 97.0f, 41.0f)],
            [1631u] = [new QuestObjective("Centaur Bandits", "", 100, 1534u, 9u, 158.0f, 92.0f)],
            [1632u] = [new QuestObjective("Amazon Raiders", "", 100, 1535u, 9u, 97.0f, 41.0f)],
            [1645u] = [new QuestObjective("Gela Hunter", "", 100, 5167u, 32u, 102.0f, 138.0f)],
            [1587u] = [new QuestObjective("Vagrant White Bulls", "", 200, 1536u, 9u, 184.0f, -11.0f)],
            [1589u] = [new QuestObjective("Centaur Bandits", "", 100, 1534u, 9u, 158.0f, 92.0f), new QuestObjective("Amazon Raiders", "", 1, 1535u, 9u, 97.0f, 41.0f)],
            [1633u] = [new QuestObjective("Vagrant White Bulls", "", 100, 1536u, 9u, 184.0f, -11.0f)],
            [1591u] = [new QuestObjective("Vagrant Brown Bulls", "", 200, 1537u, 9u, 174.0f, -159.0f)],
            [1593u] = [new QuestObjective("Vagrant White Bulls", "", 100, 1536u, 9u, 184.0f, -11.0f), new QuestObjective("Vagrant Brown Bulls", "", 1, 1537u, 9u, 174.0f, -159.0f)],
            [1643u] = [new QuestObjective("Mycenaean Female Mages", "", 300, 1545u, 9u, -155.0f, 63.0f)],
            [1597u] = [new QuestObjective("Undead Raiders", "", 200, 1539u, 9u, -90.0f, -32.0f)],
            [1601u] = [new QuestObjective("Undead Halberdiers", "", 200, 1540u, 9u, -65.0f, -124.0f)],
            [1635u] = [new QuestObjective("Undead Halberdiers", "", 100, 1540u, 9u, -65.0f, -124.0f)],
            [1604u] = [new QuestObjective("Undead Dark Mages", "", 200, 1541u, 9u, 48.0f, -114.0f)],
            [1605u] = [new QuestObjective("Immortal Nolsan!", "", 1, 1542u, 9u, 69.0f, -186.0f)],
            [1636u] = [new QuestObjective("Undead Dark Mages", "", 100, 1541u, 9u, 48.0f, -114.0f)],
            [1610u] = [new QuestObjective("Immortal Nolsan", "", 1, 1542u, 9u, 69.0f, -186.0f)],
            [1637u] = [new QuestObjective("Undead Dark Mages", "", 100, 1541u, 9u, 48.0f, -114.0f)],
            [1614u] = [new QuestObjective("Revived Khazra", "", 200, 1538u, 9u, -166.0f, 160.0f)],
            [1615u] = [new QuestObjective("Revived Khazra", "", 200, 1538u, 9u, -166.0f, 160.0f)],
            [1638u] = [new QuestObjective("Revived Khazras", "", 100, 1538u, 9u, -166.0f, 160.0f)],
            [1644u] = [new QuestObjective("Scorpion Lord's Servants", "", 300, 1547u, 9u, -163.0f, -82.0f)],
            [1617u] = [new QuestObjective("Lurking Mountain Scorpions", "", 200, 1543u, 9u, -109.0f, -158.0f)],
            [1618u] = [new QuestObjective("Lurking Mountain Scorpions", "", 200, 1543u, 9u, -109.0f, -158.0f)],
            [1620u] = [new QuestObjective("Golden Scorpion Sukur", "", 1, 1544u, 9u, -190.0f, -195.0f)],
            [1639u] = [new QuestObjective("Lurking Mountain Scorpions", "", 100, 1543u, 9u, -109.0f, -158.0f)],
            [1622u] = [new QuestObjective("Mycenaean Female Mages", "", 200, 1545u, 9u, -155.0f, 63.0f)],
            [1623u] = [new QuestObjective("Mycenaean Royal Sorcerer", "", 1, 1546u, 9u, -188.0f, 67.0f)],
            [1640u] = [new QuestObjective("Mycenaean Female Mages", "", 100, 1545u, 9u, -155.0f, 63.0f)],
            [1625u] = [new QuestObjective("Scorpion Lord's Servants", "", 200, 1547u, 9u, -163.0f, -82.0f)],
            [1626u] = [new QuestObjective("Scorpion Lord Selket!", "", 1, 1548u, 9u, -183.0f, -93.0f)],
            [1641u] = [new QuestObjective("Scorpion Lord's Servants", "", 100, 1547u, 9u, -163.0f, -82.0f)],
            [1000u] = [new QuestObjective("Crispy Wood Men", "", 10, 1010u, 1u, 184.0f, 12.0f)],
            [1003u] = [new QuestObjective("Vipers", "", 1, 1019u, 2u, 23.0f, 150.0f)],
            [1009u] = [new QuestObjective("Little Bees outside the Athens Starting Area", "", 1, 1013u, 1u, 185.0f, 112.0f)],
            [1020u] = [new QuestObjective("Lamia's Dressing Boxes", "", 1, 1018u, 2u, -31.0f, -28.0f)],
            [1048u] = [new QuestObjective("Huge Spider", "", 1, 1030u, 11u, 85.0f, 42.0f)],
            [1049u] = [new QuestObjective("Boa", "", 1, 1031u, 11u, 184.0f, 97.0f)],
            [1051u] = [new QuestObjective("Vicious Wolves", "", 1, 1032u, 11u, 1.0f, 1.0f)],
            [1062u] = [new QuestObjective("Huge Lions", "", 1, 1033u, 11u, 6.0f, 18.0f)],
            [1103u] = [new QuestObjective("Dark Necromancers", "", 1, 1054u, 3u, -15.0f, 155.0f)],
            [1185u] = [new QuestObjective("Crispy Wood Men", "", 1, 1010u, 1u, 186.0f, -2.0f)],
            [1234u] = [new QuestObjective("Robber Lolos", "", 1, 1035u, 11u, 104.0f, -134.0f)],
            [1476u] = [new QuestObjective("Wasps", "", 1, 1014u, 1u, 164.0f, 170.0f)],
            [1477u] = [new QuestObjective("Wasps", "", 1, 1014u, 1u, 164.0f, 170.0f)],
            [1478u] = [new QuestObjective("Snakes", "", 1, 1015u, 2u, 55.0f, -123.0f)],
            [1479u] = [new QuestObjective("Snakes", "", 1, 1015u, 2u, 55.0f, -123.0f)],
            [1480u] = [new QuestObjective("Wild Oxen", "", 1, 1016u, 2u, -96.0f, -196.0f)],
            [1481u] = [new QuestObjective("Wild Oxen", "", 1, 1016u, 2u, -96.0f, -196.0f)],
            [1482u] = [new QuestObjective("Lumia's Dressing Boxes", "", 1, 0u, 2u, -31.0f, -28.0f)],
            [1483u] = [new QuestObjective("Lumia's Dressing Boxes", "", 1, 0u, 2u, -31.0f, -28.0f)],
            [1484u] = [new QuestObjective("Vipers", "", 1, 1019u, 2u, 23.0f, 150.0f)],
            [1485u] = [new QuestObjective("Vipers", "", 1, 1019u, 2u, 23.0f, 150.0f)],
            [1486u] = [new QuestObjective("Skeletons", "", 1, 1020u, 2u, 122.0f, 110.0f)],
            [1487u] = [new QuestObjective("Huge Spiders", "", 1, 1030u, 11u, 85.0f, 42.0f)],
            [1488u] = [new QuestObjective("Huge Spiders", "", 1, 1030u, 11u, 85.0f, 42.0f)],
            [1489u] = [new QuestObjective("Huge Spiders", "", 1, 1030u, 11u, 85.0f, 42.0f)],
            [1490u] = [new QuestObjective("Boas", "", 1, 1031u, 11u, 184.0f, 97.0f)],
            [1491u] = [new QuestObjective("Boas", "", 1, 1031u, 11u, 184.0f, 97.0f)],
            [1492u] = [new QuestObjective("Boas", "", 1, 1031u, 11u, 184.0f, 97.0f)],
            [1493u] = [new QuestObjective("Vicious Wolves", "", 1, 1032u, 11u, 76.0f, 136.0f)],
            [1494u] = [new QuestObjective("Vicious Wolves", "", 1, 1032u, 11u, 76.0f, 136.0f)],
            [1495u] = [new QuestObjective("Vicious Wolves", "", 1, 1032u, 11u, 76.0f, 136.0f)],
            [1496u] = [new QuestObjective("Huge Lions", "", 1, 1033u, 11u, 6.0f, 18.0f)],
            [1497u] = [new QuestObjective("Huge Lions", "", 1, 1033u, 11u, 6.0f, 18.0f)],
            [1498u] = [new QuestObjective("Huge Lions", "", 1, 1033u, 11u, 6.0f, 18.0f)],
            [1499u] = [new QuestObjective("Bad Tempered Deer", "", 1, 1034u, 11u, 101.0f, -53.0f)],
            [1500u] = [new QuestObjective("Bad Tempered Deer", "", 1, 1034u, 11u, 101.0f, -53.0f)],
            [1501u] = [new QuestObjective("Bad Tempered Deer", "", 1, 1034u, 11u, 101.0f, -53.0f)],
            [1502u] = [new QuestObjective("Frogs", "", 1, 1037u, 11u, 13.0f, -145.0f)],
            [1503u] = [new QuestObjective("Frogs", "", 1, 1037u, 11u, 13.0f, -145.0f)],
            [1504u] = [new QuestObjective("Frogs", "", 1, 1037u, 11u, 13.0f, -145.0f)],
            [1505u] = [new QuestObjective("Little Crocodiles", "", 1, 1038u, 11u, -107.0f, -173.0f)],
            [1506u] = [new QuestObjective("Little Crocodiles", "", 1, 1038u, 11u, -107.0f, -173.0f)],
            [1507u] = [new QuestObjective("Little Crocodiles", "", 1, 1038u, 11u, -107.0f, -173.0f)],
            [1634u] = [new QuestObjective("Vagrant White Bulls", "", 100, 1536u, 9u, 184.0f, -11.0f)],
            [1650u] = [new QuestObjective("Nemean Lion", "", 1, 1550u, 210u, 121.0f, -124.0f)],
        };

    /// <summary>The objectives of a quest, empty when it has none.</summary>
    public static IReadOnlyList<QuestObjective> For(uint questId) =>
        ByQuestId.TryGetValue(questId, out var objectives)
            ? objectives
            : [];

    /// <summary>Reads one objective's counter out of the packed progress.</summary>
    public static int Counter(int progress, int slot) =>
        (progress >> (slot * CounterBits)) & CounterMaximum;

    /// <summary>Writes one objective's counter back into the progress.</summary>
    public static int WithCounter(int progress, int slot, int value)
    {
        var clamped = Math.Clamp(value, 0, CounterMaximum);
        var shift = slot * CounterBits;
        return (progress & ~(CounterMaximum << shift)) |
            (clamped << shift);
    }

    /// <summary>True when every objective has been satisfied.</summary>
    public static bool IsSatisfied(
        IReadOnlyList<QuestObjective> objectives,
        int progress)
    {
        for (var slot = 0; slot < objectives.Count; slot++)
        {
            if (Counter(progress, slot) < objectives[slot].Required)
            {
                return false;
            }
        }

        return true;
    }

    /// <summary>True when a killed monster satisfies this objective.</summary>
    public static bool Matches(
        QuestObjective objective,
        uint mapId,
        string? monsterName,
        float x,
        float z)
    {
        if (objective.MapId != mapId)
        {
            return false;
        }

        if (Needle(NameOf(objective)) is { Length: > 0 } &&
            Needle(monsterName) is { Length: > 0 })
        {
            // The quest text is sloppy about plurals - "Woodland
            // Wolves" for the client's "Woodland Wolf" - so the two
            // names are compared through every shape the plural can
            // stand for, not just the folded text.
            return SameName(NameOf(objective), monsterName);
        }

        var dx = objective.X - x;
        var dz = objective.Z - z;
        return (dx * dx) + (dz * dz) <= MatchRadius * MatchRadius;
    }

    /// <summary>
    /// The name a kill has to carry to credit this objective: the client's
    /// own name for the target when the quest text calls it something else.
    /// </summary>
    public static string NameOf(QuestObjective objective) =>
        string.IsNullOrWhiteSpace(objective.Match)
            ? objective.Target
            : objective.Match;

    /// <summary>
    /// Reduces a display name to letters and digits so plurals and colour
    /// markup do not stop a match.
    /// </summary>
    /// <remarks>
    /// The quest text says "Kill 10 Dumb Wood Men" while the monster is
    /// called "Dumb Wood Man", and 521 says "Wooden Puppets" for the
    /// monster "Wooden Puppet", so a trailing plural is dropped and the
    /// irregular "men" is folded onto "man".
    /// </remarks>
    internal static string Needle(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        var plain = ColorMarkup().Replace(value, string.Empty);
        var builder = new StringBuilder(plain.Length);
        var separator = false;
        foreach (var character in plain)
        {
            if (char.IsLetterOrDigit(character))
            {
                builder.Append(char.ToLowerInvariant(character));
                separator = true;
            }
            else if (separator)
            {
                builder.Append(' ');
                separator = false;
            }
        }

        var words = new List<string>();
        foreach (var word in builder.ToString().Split(
                     ' ', StringSplitOptions.RemoveEmptyEntries))
        {
            words.Add(word switch
            {
                "men" => "man",
                _ when word.Length > 3 && word.EndsWith('s') =>
                    word[..^1],
                _ => word
            });
        }

        return string.Join(' ', words);
    }

    [GeneratedRegex(
        @"\|c[0-9a-fA-F]{8}",
        RegexOptions.CultureInvariant)]
    private static partial Regex ColorMarkup();
}
