// Generated by tools/gen_quest_objective_frames.py; do not edit
// by hand. The frames are the reference server's own packets,
// captured while a kill quest was accepted and worked on.

using System.Buffers.Binary;
using Godswar.Server.Protocol;

namespace Godswar.Server.Packets;

internal static partial class PacketBuilder
{
    /// <summary>S2C 10081, the reference server's quest detail frame (packet 84550).</summary>
    private static readonly byte[] Objective10081Bytes = Convert.FromHexString(
        "68016127BE130000080200000000000008000000000000000000000003040000000000000000000000000000" +
        "0A00000000000000000000000000000000000000000000000000000034080000FFFFFFFFFFFFFFFFFFFFFFFF" +
        "FFFFFFFFFFFFFFFF030101010000000000000000000000000000000000000000000000000000000000000000" +
        "000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0101000100000000" +
        "00000000000000000000000000000000000000000000000000000000000000000000000000000000FFFFFFFF" +
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF010100010000000000000000000000000000000000000000" +
        "000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" +
        "FFFFFFFF01010001000000000000000000000000000000000000000000000000000000000000000000000000" +
        "0000000000000000");

    /// <summary>S2C 10082, the reference server's accepted quest frame (packet 84573).</summary>
    private static readonly byte[] Objective10082Bytes = Convert.FromHexString(
        "88026227BE130000BE1300000802000000000000080000000000000000000000030400000000000000000000" +
        "000000000A000000000000000000000000000000000000000000000034080000FFFFFFFFFFFFFFFFFFFFFFFF" +
        "FFFFFFFFFFFFFFFF030101010000000000000000000000000000000000000000000000000000000000000000" +
        "000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0101000100000000" +
        "00000000000000000000000000000000000000000000000000000000000000000000000000000000FFFFFFFF" +
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF010100010000000000000000000000000000000000000000" +
        "000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" +
        "FFFFFFFF01010001000000000000000000000000000000000000000000000000000000000000000000000000" +
        "000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF010100000000000000000000" +
        "00000000000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFF00000000FFFFFFFF" +
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF01010000000000000000000000000000000000000000000000000000" +
        "000000000000000000000000FFFFFFFFFFFFFFFF00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" +
        "01010000000000000000000000000000000000000000000000000000000000000000000000000000FFFFFFFF" +
        "FFFFFFFF00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF01010000000000000000000000000000" +
        "000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFF");

    /// <summary>S2C 10087, the reference server's progress step frame (packet 84740).</summary>
    private static readonly byte[] Objective10087Bytes = Convert.FromHexString(
        "1400672708020000BE1300000100000003040000");

    /// <summary>S2C 10081, the detail of a kill quest.</summary>
    /// <remarks>
    /// Payload +0 npc, +4 quest, +24 target monster id and +40 how
    /// many are wanted.
    /// </remarks>
    public static byte[] QuestObjectiveDetail(
        uint npcId,
        uint questId,
        uint monsterId,
        int required)
    {
        var packet = (byte[])Objective10081Bytes.Clone();
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(4, 4), npcId);
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(8, 4), questId);
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(28, 4), monsterId);
        BinaryPrimitives.WriteInt32LittleEndian(
            packet.AsSpan(44, 4), required);
        return packet;
    }

    /// <summary>S2C 10087, one step of quest progress.</summary>
    /// <remarks>
    /// Payload +0 quest, +4 npc, +8 the step (always 1 in the
    /// capture - one kill) and +12 the target monster id.
    /// </remarks>
    public static byte[] QuestObjectiveProgress(
        uint questId,
        uint npcId,
        uint monsterId,
        int step = 1)
    {
        var packet = (byte[])Objective10087Bytes.Clone();
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(4, 4), questId);
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(8, 4), npcId);
        BinaryPrimitives.WriteInt32LittleEndian(
            packet.AsSpan(12, 4), step);
        BinaryPrimitives.WriteUInt32LittleEndian(
            packet.AsSpan(16, 4), monsterId);
        return packet;
    }
}
