"""Clone a character onto another account, optionally switching camp.

Copies the character row - level, currencies and progression all live there -
plus the character-scoped tables that hold real content: items, skills, talents,
the available skill/talent lists and the zodiac grid. Ledgers, audits, claims and
daily entries are deliberately left behind, because a cloned character must not
inherit another character's history.

`character_equip`, `character_item_loadout` and `character_stat_summary` are
views over character_items, so they follow automatically.

Usage:
  python tools/clone_character.py --database godswar_local \
      --source 2 --account 6 --name test2 --camp 1
  python tools/clone_character.py ... --apply
"""
from __future__ import annotations

import argparse
import subprocess
import sys

# table -> the column that points at the character. Only base tables that
# actually hold content for a lived-in character; the available-skill,
# available-talent, equip, loadout and summary relations are views over these and
# follow automatically.
COPY_TABLES = [
    ("character_items", "user_id"),
    ("character_skills", "user_id"),
    ("character_talents", "user_id"),
    ("character_zodiac_skill_grids", "user_id"),
    ("character_quests", "character_id"),
    ("character_economy_baseline", "character_id"),
]

# car_acter_base fields the clone must not inherit verbatim.
BASE_OVERRIDES = ("account_id", "name", "camp", "server_id")


def psql(database: str, sql: str, strict: bool = True) -> tuple[int, str]:
    done = subprocess.run(
        ["docker", "exec", "-i", "godswar-postgres", "psql", "-U", "godswar",
         "-d", database, "-t", "-A", "-F", "|", "-v", "ON_ERROR_STOP=1"],
        input=sql, capture_output=True, text=True, encoding="utf-8")
    output = (done.stdout or "") + (done.stderr or "")
    if strict and done.returncode != 0:
        raise SystemExit(output.strip())
    return done.returncode, output


def columns(database: str, table: str) -> list[str]:
    _, out = psql(database,
                  "SELECT column_name FROM information_schema.columns "
                  f"WHERE table_schema='public' AND table_name='{table}' "
                  "ORDER BY ordinal_position;")
    return [line.strip() for line in out.splitlines() if line.strip()]


def quote(name: str) -> str:
    return f'"{name}"'


def build_base_insert(database: str, args, camp: int, server_id: int) -> str:
    """Copy every character_base column, overriding identity and camp."""
    overrides = {
        "account_id": str(args.account),
        "name": f"'{args.name}'",
        "camp": str(camp),
        "server_id": str(server_id),
    }
    targets, sources = [], []
    for column in columns(database, "character_base"):
        if column == "id":
            continue                      # generated by identity
        targets.append(quote(column))
        sources.append(overrides.get(column, quote(column)))
    return (f"INSERT INTO public.character_base ({', '.join(targets)}) "
            f"SELECT {', '.join(sources)} FROM public.character_base "
            f"WHERE id={args.source};")


def build_child_insert(database: str, table: str, column: str, args,
                       new_key: str) -> str:
    """Copy a child table's rows, re-pointing the character column at new_key.

    The available-skill and available-talent tables also denormalise the
    character's name, so that column is rewritten too - otherwise the clone would
    carry the source character's name in its own projection rows.
    """
    overrides = {
        column: new_key,
        "character_name": f"'{args.name}'",
    }
    targets = [c for c in columns(database, table) if c != "id"]
    sources = [overrides.get(c, quote(c)) for c in targets]
    return (f"INSERT INTO public.{table} "
            f"({', '.join(quote(c) for c in targets)}) "
            f"SELECT {', '.join(sources)} FROM public.{table} "
            f"WHERE {column}={args.source};")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--database", default="godswar_local")
    parser.add_argument("--source", type=int, required=True)
    parser.add_argument("--account", type=int, required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--camp", type=int, help="0 Sparta, 1 Athens")
    parser.add_argument("--server-id", type=int)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    _, out = psql(args.database,
                  "SELECT name, account_id, camp, server_id, fighter_job_lv "
                  f"FROM character_base WHERE id={args.source};")
    row = [line for line in out.splitlines() if line.strip()]
    if not row:
        raise SystemExit(f"character {args.source} not found")
    src_name, src_account, src_camp, src_server, src_level = row[0].split("|")
    print(f"source: id={args.source} name={src_name} account={src_account} "
          f"camp={src_camp} server={src_server} level={src_level}")

    _, out = psql(args.database,
                  f"SELECT count(*) FROM character_base WHERE "
                  f"account_id={args.account} AND name='{args.name}';")
    if int(out.strip() or 0):
        raise SystemExit(
            f"account {args.account} already has a character named {args.name}")

    camp = args.camp if args.camp is not None else int(src_camp)
    server_id = args.server_id if args.server_id is not None else int(src_server)

    # One expression resolves the clone's generated key, so every child insert can
    # point at it without a second round trip or a placeholder to rewrite.
    new_key = ("(SELECT id FROM public.character_base "
               f"WHERE account_id={args.account} AND name='{args.name}')")

    statements = [
        "BEGIN;",
        build_base_insert(args.database, args, camp, server_id),
    ]
    for table, column in COPY_TABLES:
        statements.append(
            build_child_insert(database=args.database, table=table,
                               column=column, args=args, new_key=new_key))
    statements.append("COMMIT;")
    script = "\n".join(statements)

    if not args.apply:
        print("\n--- generated SQL ---")
        for line in script.splitlines():
            print(line[:200])
        print("\n(dry run - pass --apply to write)")
        return 0

    code, out = psql(args.database, script)
    if code != 0:
        print(f"\nFAILED:\n{out}")
        return 1

    _, out = psql(args.database,
                  "SELECT id, account_id, name, camp, fighter_job_lv "
                  f"FROM character_base WHERE account_id={args.account} "
                  f"AND name='{args.name}';")
    print("\nnew character: " + out.strip().replace("|", "  "))

    _, out = psql(args.database,
                  "SELECT c.id, "
                  "(SELECT count(*) FROM character_items i WHERE i.user_id=c.id), "
                  "(SELECT count(*) FROM character_skills s WHERE s.user_id=c.id) "
                  f"FROM character_base c WHERE c.account_id={args.account} "
                  f"AND c.name='{args.name}';")
    print("items/skills: " + out.strip().replace("|", "  "))
    return 0


if __name__ == "__main__":
    sys.exit(main())
