"""Lift the reference server's kill-quest frames out of the capture.

These three frames are what actually drives the client's "not finished yet /
progress / finished" display, and our own accept flow had none of them:

  10081 (360)  the quest detail: the target monster id at payload +24 and how
               many are wanted at payload +40
  10082 (648)  the accepted quest, the same two values four bytes later (+28 and
               +44) because this frame carries the responder as well
  10087 (20)   one progress step, sent for every counted kill: quest, npc, a
               delta of 1, and the monster id

The capture was taken from the reference server on 2026-09-14 while quest 520
("kill 10 Dumb Wood Men") was accepted and two of them were killed.
"""

import sys

CAPTURE = (r"D:\Godswar-Reborn-main\captures"
           r"\quest-kill-capture-20260914.txt")
OUTPUT = (r"D:\Godswar-Reborn-main\src\Godswar.Server\Packets"
          r"\PacketBuilder.QuestObjectiveFrames.cs")

# (packet id, opcode, expected length, field / meaning)
SOURCES = [
    (84550, 10081, 360, "quest detail"),
    (84573, 10082, 648, "accepted quest"),
    (84740, 10087, 20, "progress step"),
]


def load(sequence):
    with open(CAPTURE, "r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 6:
                continue
            try:
                if int(parts[0]) != sequence:
                    continue
            except ValueError:
                continue
            return bytes.fromhex(parts[5].strip())
    raise SystemExit(f"packet {sequence} not found")


def main():
    lines = []
    lines.append("// Generated by tools/gen_quest_objective_frames.py; do not edit")
    lines.append("// by hand. The frames are the reference server's own packets,")
    lines.append("// captured while a kill quest was accepted and worked on.")
    lines.append("")
    lines.append("using System.Buffers.Binary;")
    lines.append("using Godswar.Server.Protocol;")
    lines.append("")
    lines.append("namespace Godswar.Server.Packets;")
    lines.append("")
    lines.append("internal static partial class PacketBuilder")
    lines.append("{")
    for sequence, opcode, expected, meaning in SOURCES:
        frame = load(sequence)
        if len(frame) != expected:
            raise SystemExit(
                f"packet {sequence} is {len(frame)} bytes, expected {expected}")
        if int.from_bytes(frame[2:4], "little") != opcode:
            raise SystemExit(f"packet {sequence} is not opcode {opcode}")
        print(f"packet {sequence}: opcode {opcode}, {len(frame)} bytes, "
              f"{meaning}")
        hexs = frame.hex().upper()
        chunks = [hexs[index:index + 88] for index in range(0, len(hexs), 88)]
        lines.append(f"    /// <summary>S2C {opcode}, the reference server's "
                     f"{meaning} frame (packet {sequence}).</summary>")
        lines.append(f"    private static readonly byte[] "
                     f"Objective{opcode}Bytes = Convert.FromHexString(")
        for index, chunk in enumerate(chunks):
            suffix = " +" if index + 1 < len(chunks) else ");"
            lines.append(f'        "{chunk}"{suffix}')
        lines.append("")
    lines.append("    /// <summary>S2C 10081, the detail of a kill quest.</summary>")
    lines.append("    /// <remarks>")
    lines.append("    /// Payload +0 npc, +4 quest, +24 target monster id and +40 how")
    lines.append("    /// many are wanted.")
    lines.append("    /// </remarks>")
    lines.append("    public static byte[] QuestObjectiveDetail(")
    lines.append("        uint npcId,")
    lines.append("        uint questId,")
    lines.append("        uint monsterId,")
    lines.append("        int required)")
    lines.append("    {")
    lines.append("        var packet = (byte[])Objective10081Bytes.Clone();")
    lines.append("        BinaryPrimitives.WriteUInt32LittleEndian(")
    lines.append("            packet.AsSpan(4, 4), npcId);")
    lines.append("        BinaryPrimitives.WriteUInt32LittleEndian(")
    lines.append("            packet.AsSpan(8, 4), questId);")
    lines.append("        BinaryPrimitives.WriteUInt32LittleEndian(")
    lines.append("            packet.AsSpan(28, 4), monsterId);")
    lines.append("        BinaryPrimitives.WriteInt32LittleEndian(")
    lines.append("            packet.AsSpan(44, 4), required);")
    lines.append("        return packet;")
    lines.append("    }")
    lines.append("")
    lines.append("    /// <summary>S2C 10087, one step of quest progress.</summary>")
    lines.append("    /// <remarks>")
    lines.append("    /// Payload +0 quest, +4 npc, +8 the step (always 1 in the")
    lines.append("    /// capture - one kill) and +12 the target monster id.")
    lines.append("    /// </remarks>")
    lines.append("    public static byte[] QuestObjectiveProgress(")
    lines.append("        uint questId,")
    lines.append("        uint npcId,")
    lines.append("        uint monsterId,")
    lines.append("        int step = 1)")
    lines.append("    {")
    lines.append("        var packet = (byte[])Objective10087Bytes.Clone();")
    lines.append("        BinaryPrimitives.WriteUInt32LittleEndian(")
    lines.append("            packet.AsSpan(4, 4), questId);")
    lines.append("        BinaryPrimitives.WriteUInt32LittleEndian(")
    lines.append("            packet.AsSpan(8, 4), npcId);")
    lines.append("        BinaryPrimitives.WriteInt32LittleEndian(")
    lines.append("            packet.AsSpan(12, 4), step);")
    lines.append("        BinaryPrimitives.WriteUInt32LittleEndian(")
    lines.append("            packet.AsSpan(16, 4), monsterId);")
    lines.append("        return packet;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
