"""Regenerate the captured opcode-10082 quest answers.

The reference server answers a quest with that quest's own 648-byte record:
quest 1519 carries the four class-weapon slots (1000/1400/1700/1800) while
quest 518 carries the single newbie gift bag (3876), and the client builds its
quest window from whichever slots arrive. The local server used one template
plus a partial reward patch, which left every quest without captured reward
records - 1519 among them - wearing quest 518's slots; the client then faulted
at 004AC835 when the hand-in refreshed that record.

This script lifts the reference's own answer per quest and writes the table the
packet builder replays. The first capture per quest id wins: the reference's
later repeats of the same quest can be its own template fallback, and the
earliest sample is the one that matches the quest's sibling camp twin.

Usage:
    python tools/gen_quest_answer_frames.py [output.cs]
"""

import re
import subprocess
import sys

OUTPUT = (r"D:\Godswar-Reborn-main\src\Godswar.Server\Packets"
          r"\PacketBuilder.QuestAnswerFrames.Generated.cs")
PSQL = ["docker", "exec", "godswar-postgres", "psql", "-U", "godswar",
        "-d", "godswar", "-t", "-A", "-F", "|", "-c"]

# The reference server's game port. The capture database also holds frames from
# this project's local server (port 7000) recorded for comparison; those are our
# own output and must never be replayed as reference data.
REFERENCE_PORT = "13333"
QUERY = (
    "select encode(clear_bytes,'hex') from packet_transactions "
    "where direction='S2C' "
    f"and split_part(source_endpoint,':',2)='{REFERENCE_PORT}' "
    "and opcode=10082 order by id;")

# The client's own quest ids stay below this: larger values are the frame's
# memory-pointer fields, not quests.
MAXIMUM_QUEST_ID = 20000
FRAME_BYTES = 648
# The reward slots start right after the record's own header: the captured answers
# carry four free slots from +68, and the local builder copies the same area into
# the frame it sends.
AREA_OFFSET = 64
AREA_BYTES = 576


def fetch() -> list[str]:
    completed = subprocess.run(PSQL + [QUERY], capture_output=True, text=True,
                               check=True)
    return [line.strip() for line in completed.stdout.splitlines() if line.strip()]


def main() -> int:
    output = sys.argv[1] if len(sys.argv) > 1 else OUTPUT
    frames: list[tuple[int, int, str]] = []
    for hex_text in fetch():
        frame = bytes.fromhex(hex_text)
        if len(frame) != FRAME_BYTES:
            continue
        quest = int.from_bytes(frame[12:16], "little")
        kind = int.from_bytes(frame[20:24], "little")
        if quest == 0 or quest > MAXIMUM_QUEST_ID or kind not in (4, 8):
            continue
        frames.append((quest, kind, hex_text.lower()))

    # The whole frame is replayed only for the objective-less shape: a kill quest's
    # objective area comes from StarterQuestObjectives instead, because the
    # reference's own objective sample (quest 520) carries its required count but a
    # zero target, and this server fills the monster it actually counts kills for.
    answers: dict[int, str] = {}
    for quest, kind, text in frames:
        if kind == 4:
            answers.setdefault(quest, text)

    # The reward area is per quest and its slot count differs even inside one chain:
    # 519 offers the four class weapons, 520 one light armour, 1521 nothing at all.
    # Keep the sample whose objective kind matches the shape about to be sent.
    areas: dict[tuple[int, int], str] = {}
    for quest, kind, text in frames:
        areas.setdefault(
            (quest, kind),
            text[AREA_OFFSET * 2:(AREA_OFFSET + AREA_BYTES) * 2])

    # The empty area comes from a captured answer that carried no reward at all; a
    # quest without its own sample keeps that instead of another quest's items.
    empty = ""
    for quest, kind, text in frames:
        area = bytes.fromhex(text[AREA_OFFSET * 2:(AREA_OFFSET + AREA_BYTES) * 2])
        if all(area[8 + slot * 72:8 + slot * 72 + 20] == b"\xff" * 20
               for slot in range(4)):
            empty = text[AREA_OFFSET * 2:(AREA_OFFSET + AREA_BYTES) * 2]
            break

    with open(output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(
            "// <auto-generated>\n"
            "//     Generated from the reference capture's opcode-10082 quest\n"
            "//     answers (packet_transactions) by tools/gen_quest_answer_frames.py.\n"
            "//     One 648-byte record per quest, exactly as the reference sent it:\n"
            "//     +4 giver, +8 responder, +12 quest, +16 category, +20 objective\n"
            "//     kind, +32 target monster, +48 required kills, and the reward slots\n"
            "//     from +68. Both the slots and the objective kind are per quest - 519\n"
            "//     offers the class-weapon choice, 520 one light armour, 1521 and 1522\n"
            "//     nothing - so a quest without its own sample must stay empty rather\n"
            "//     than wear another quest's answer.\n"
            "//     Do not edit by hand.\n"
            "// </auto-generated>\n\n"
            "namespace Godswar.Server.Packets;\n\n"
            "internal static partial class PacketBuilder\n"
            "{\n"
            "    /// <summary>\n"
            "    /// Captured opcode-10082 answers keyed by the client's quest id, for the\n"
            "    /// quests whose answer carries no kill objective.\n"
            "    /// </summary>\n"
            "    private static readonly Dictionary<uint, string> CapturedQuestAnswers = new()\n"
            "    {\n")
        for quest in sorted(answers):
            handle.write(f"        [{quest}u] =\n")
            text = answers[quest]
            for offset in range(0, len(text), 64):
                chunk = text[offset:offset + 64]
                suffix = "," if offset + 64 >= len(text) else " +"
                handle.write(f'            "{chunk}"{suffix}\n')
        handle.write(
            "    };\n\n"
            "    /// <summary>\n"
            "    /// Captured reward areas (four 72-byte slots) keyed by quest and by the\n"
            "    /// objective kind of the sample that carried them.\n"
            "    /// </summary>\n"
            "    private static readonly Dictionary<(uint QuestId, uint Kind), string>\n"
            "        CapturedQuestRewardAreas = new()\n"
            "        {\n")
        for key in sorted(areas):
            quest, kind = key
            handle.write(f"            [({quest}u, {kind}u)] =\n")
            text = areas[key]
            for offset in range(0, len(text), 64):
                chunk = text[offset:offset + 64]
                suffix = "," if offset + 64 >= len(text) else " +"
                handle.write(f'                "{chunk}"{suffix}\n')
        handle.write(
            "        };\n\n"
            "    /// <summary>\n"
            "    /// The reward area of a captured answer that carried no reward at all:\n"
            "    /// four free slots.\n"
            "    /// </summary>\n"
            "    private static readonly byte[] EmptyQuestRewardArea =\n"
            "        Convert.FromHexString(\n")
        for offset in range(0, len(empty), 64):
            chunk = empty[offset:offset + 64]
            suffix = "" if offset + 64 >= len(empty) else " +"
            handle.write(f'            "{chunk}"{suffix}\n')
        handle.write(
            "            );\n}\n")

    print(f"wrote {len(answers)} answers, {len(areas)} reward areas, "
          f"empty area {len(empty) // 2} bytes to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
