"""Generate the per-quest reward record table from the reference capture.

The 10082 accept answer carries eight 72-byte record slots starting at payload
+60 (payload = the frame without its 4-byte length+opcode header). Each slot
holds the reward item at +8, five -1 words at +12..+28 and a fill flag at +32;
packet 247's newbie gift bag 240f0000 sits at payload 68, which is slot 0 + 8.

Two captures exist: packet 247 answered quest 518 and packet 1373 answered quest
519, and a word-by-word diff of the two frames shows every difference lies in the
header words +4/+8/+12 or inside those slots. So the 576-byte slot area is the
per-quest part, and it is lifted verbatim.

Slots the client does not fill stay 0xFFFFFFFF, which the capture shows for the
unused slots of 518, so no sentinel has to be invented.

The same 72-byte slot is what the login snapshot's 10090 carries per quest, so
its first 72 bytes are the record for a carried quest as well.
"""

import struct
import sys

CAPTURE = r"D:\Godswar-Reborn-main\captures\quest-capture-20260913.txt"
KILL_CAPTURE = (r"D:\Godswar-Reborn-main\captures"
                r"\quest-kill-capture-20260914.txt")
OUTPUT = (r"D:\Godswar-Reborn-main\src\Godswar.Server\Domain\World\Content"
          r"\StarterQuestRewardRecords.cs")

RECORD_BASE = 60
RECORD_SLOTS = 8
RECORD_BYTES = 72
AREA_BYTES = RECORD_SLOTS * RECORD_BYTES

# (capture file, packet id, quest id)
SOURCES = [
    (CAPTURE, 247, 518),
    (CAPTURE, 1373, 519),
    (KILL_CAPTURE, 84573, 520),
]


def load(path, seq):
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 6:
                continue
            try:
                if int(parts[0]) != seq:
                    continue
            except ValueError:
                continue
            return bytes.fromhex(parts[5].strip())
    raise SystemExit(f"packet {seq} not found")


def main():
    rows = []
    for path, seq, quest in SOURCES:
        frame = load(path, seq)
        payload = frame[4:]
        header_quest = struct.unpack_from("<I", payload, 8)[0]
        if header_quest != quest:
            raise SystemExit(
                f"packet {seq} answers quest {header_quest}, expected {quest}")
        area = payload[RECORD_BASE:RECORD_BASE + AREA_BYTES]
        if len(area) != AREA_BYTES:
            raise SystemExit(f"packet {seq} is too short")
        filled = 0
        for slot in range(RECORD_SLOTS):
            # The reward item sits at slot + 8; an unused slot leaves it zero in
            # the login snapshot and -1 in the accept answer.
            item = struct.unpack_from("<I", area, (slot * RECORD_BYTES) + 8)[0]
            if item not in (0, 0xFFFFFFFF):
                filled += 1
        rows.append((quest, seq, area.hex().upper(), filled))
        print(f"quest {quest}: packet {seq}, {filled} filled slot(s)")

    lines = []
    lines.append("namespace Godswar.Server.Domain.World.Content;")
    lines.append("")
    lines.append("/// <summary>")
    lines.append("/// The reward records the accept answer (S2C 10082) carries for a")
    lines.append("/// quest, lifted byte for byte from the reference capture.")
    lines.append("/// </summary>")
    lines.append("/// <remarks>")
    lines.append("/// Generated by <c>tools/gen_quest_reward_records.py</c>; do not edit by")
    lines.append("/// hand. The area is four 72-byte slots at payload +68. Packet 247")
    lines.append("/// answered quest 518 with one slot filled - the newbie gift bag 3876 -")
    lines.append("/// and packet 1373 answered quest 519 with four, the four class weapons")
    lines.append("/// the client offers as a choice. A quest with no row here falls back to")
    lines.append("/// the captured template, because no reference sample exists for it.")
    lines.append("/// </remarks>")
    lines.append("internal static class StarterQuestRewardRecords")
    lines.append("{")
    lines.append("    /// <summary>Bytes of the record area: four 72-byte slots.</summary>")
    lines.append(f"    public const int AreaBytes = {AREA_BYTES};")
    lines.append("")
    lines.append("    /// <summary>Bytes of a single reward record slot.</summary>")
    lines.append(f"    public const int RecordBytes = {RECORD_BYTES};")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// Reward record areas keyed by the client's quest id.")
    lines.append("    /// </summary>")
    lines.append("    public static IReadOnlyDictionary<uint, byte[]> ByQuestId { get; } =")
    lines.append("        new Dictionary<uint, byte[]>")
    lines.append("        {")
    for quest, seq, hexs, filled in rows:
        lines.append(f"            // Packet {seq}: {filled} filled slot(s).")
        lines.append(f"            [{quest}u] = Convert.FromHexString(")
        chunks = [hexs[offset:offset + 96]
                  for offset in range(0, len(hexs), 96)]
        for index, chunk in enumerate(chunks):
            suffix = " +" if index + 1 < len(chunks) else "),"
            lines.append(f'                "{chunk}"{suffix}')
    lines.append("        };")
    lines.append("")
    lines.append("    /// <summary>The area for a quest, or null when none was captured.</summary>")
    lines.append("    public static byte[]? Find(uint questId) =>")
    lines.append("        ByQuestId.TryGetValue(questId, out var area) ? area : null;")
    lines.append("}")
    lines.append("")

    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    sys.exit(main())
