"""Regenerate the captured opcode-10086 and opcode-10076 quest frames.

The reference answers a hand-in with the handed-in quest's own acknowledgement
and the next quest's own detail, and both frames differ per quest: quest 1519's
acknowledgement names reward slot 3 with exp 88 and 5 talent points while 1521's
names no slot at all, and quest 1521's detail carries kind 8 with its kill
objective where 1522's carries kind 4 and free slots. Replaying the captured
frame keeps every one of those fields the reference's own; a frame borrowed from
another quest is what faults the installed client at 004AC835.

Only the reference server's own traffic is used. The capture database also holds
frames recorded from this project's local server (source port 7000) for
comparison, and those were generated from a template - replaying them put this
server's own guesses back on the wire, which is how quest 1522 came to be
answered with a reward slot its record does not have.

Usage:
    python tools/gen_quest_handin_frames.py [output.cs]
"""

import subprocess
import sys

OUTPUT = (r"D:\Godswar-Reborn-main\src\Godswar.Server\Packets"
          r"\PacketBuilder.QuestHandInFrames.Generated.cs")
PSQL = ["docker", "exec", "godswar-postgres", "psql", "-U", "godswar",
        "-d", "godswar", "-t", "-A", "-F", "|", "-c"]

# The reference server's game port. Local-server traffic (port 7000) is this
# project's own output and must never be treated as reference data.
REFERENCE_PORT = "13333"

ACK_BYTES = 120
DETAIL_BYTES = 356
MAXIMUM_QUEST_ID = 20000


def fetch(opcode: int) -> list[bytes]:
    query = (
        "select encode(clear_bytes,'hex') from packet_transactions "
        "where direction='S2C' "
        f"and split_part(source_endpoint,':',2)='{REFERENCE_PORT}' "
        f"and opcode={opcode} order by id;")
    completed = subprocess.run(PSQL + [query], capture_output=True, text=True,
                               check=True)
    return [bytes.fromhex(line.strip())
            for line in completed.stdout.splitlines() if line.strip()]


def hex_block(text: str, indent: str) -> str:
    lines = []
    for offset in range(0, len(text), 64):
        chunk = text[offset:offset + 64]
        suffix = "," if offset + 64 >= len(text) else " +"
        lines.append(f'{indent}"{chunk}"{suffix}')
    return "\n".join(lines)


def main() -> int:
    output = sys.argv[1] if len(sys.argv) > 1 else OUTPUT

    acks: dict[int, str] = {}
    for frame in fetch(10086):
        if len(frame) != ACK_BYTES:
            continue
        quest = int.from_bytes(frame[12:16], "little")
        if quest == 0 or quest > MAXIMUM_QUEST_ID:
            continue
        acks.setdefault(quest, frame.hex())

    details: dict[int, str] = {}
    for frame in fetch(10076):
        if len(frame) != DETAIL_BYTES:
            continue
        quest = int.from_bytes(frame[8:12], "little")
        if quest == 0 or quest > MAXIMUM_QUEST_ID:
            continue
        details.setdefault(quest, frame.hex())

    with open(output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(
            "// <auto-generated>\n"
            "//     Generated from the reference server's own hand-in answers\n"
            "//     (opcodes 10086 and 10076) by tools/gen_quest_handin_frames.py.\n"
            "//     Only capture traffic from the reference port is used: the local\n"
            "//     server's frames (source port 7000) are this project's own output\n"
            "//     and replaying them fed this server's guesses back to the client.\n"
            "//     Do not edit by hand.\n"
            "// </auto-generated>\n\n"
            "namespace Godswar.Server.Packets;\n\n"
            "internal static partial class PacketBuilder\n"
            "{\n"
            "    /// <summary>\n"
            "    /// Hand-in acknowledgements, keyed by the quest being handed in. The\n"
            "    /// builder rewrites the giver, the responder, the quest, the reward\n"
            "    /// slot the client asked for and the player's own experience and\n"
            "    /// talent points; everything else is the reference's.\n"
            "    /// </summary>\n"
            "    private static readonly Dictionary<uint, string> CapturedHandInAcks = new()\n"
            "    {\n")
        for quest in sorted(acks):
            handle.write(f"        [{quest}u] =\n")
            handle.write(hex_block(acks[quest], " " * 12) + "\n")
        handle.write(
            "    };\n\n"
            "    /// <summary>\n"
            "    /// Follow-up details, keyed by the next quest the detail describes\n"
            "    /// (frame offset +8). Only the giver is rewritten.\n"
            "    /// </summary>\n"
            "    private static readonly Dictionary<uint, string> CapturedNextQuestDetails = new()\n"
            "    {\n")
        for quest in sorted(details):
            handle.write(f"        [{quest}u] =\n")
            handle.write(hex_block(details[quest], " " * 12) + "\n")
        handle.write("    };\n}\n")

    print(f"wrote {len(acks)} acknowledgements and {len(details)} details "
          f"to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
