#requires -Version 7
<#
    Generates the reviewed client-catalog item baseline consumed by
    PostgresItemTemplateBaselinePublisher (family "client-catalog-v1").

    The stock client ships item identities that the server's equipment-only
    generator (GenerateItemTemplates.ps1) never imports: consumables,
    materials, quest items, sigil stones, gathering and pet items. This tool
    emits the reviewed subset requested through an explicit ID list so the
    server can publish those identities as immutable item content.

    Outputs
      src/Godswar.Server/State/ClientCatalogItemSeed.Generated.cs
      database/postgres/076_client_catalog_item_templates.sql
#>
param(
    [string]$ClientRoot = 'D:\Godswar Origin',
    [string]$ServerRoot = 'D:\Godswar-Reborn-main',
    [Parameter(Mandatory = $true)]
    [string[]]$ItemIdsFile,
    [string]$SeedOutputPath = 'src\Godswar.Server\State\ClientCatalogItemSeed.Generated.cs',
    [string]$SqlOutputPath = 'database\postgres\076_client_catalog_item_templates.sql'
)

$ErrorActionPreference = 'Stop'

$itemBasePath = Join-Path $ClientRoot 'Localization\en_us\Settings\Sys\ItemBaseAttribute.xml'
$equipNamePath = Join-Path $ClientRoot 'Localization\en_us\Text\EquipName.dat'
$sqlRoot = Join-Path $ServerRoot (Split-Path $SqlOutputPath -Parent)
$sqlHeader = @'
-- <auto-generated />
-- Generated by tools/GenerateClientCatalogItemSeeds.ps1.
-- Reviewed client-catalog item identities that the equipment-only generator
-- (tools/GenerateItemTemplates.ps1) never imported. Consumed by the
-- immutable item-content publication family "client-catalog-v1".
'@

if (-not (Test-Path $itemBasePath)) { throw "ItemBaseAttribute.xml not found: $itemBasePath" }
if (-not (Test-Path $equipNamePath)) { throw "EquipName.dat not found: $equipNamePath" }

function ConvertTo-CSharpString([string]$value) {
    if ($null -eq $value) { return 'string.Empty' }
    return '"' + $value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function ConvertTo-SqlString([string]$value) {
    if ($null -eq $value) { return 'NULL' }
    return "'" + $value.Replace("'", "''") + "'"
}

# The reviewed consume-item shape used across the repository: slot 0, no class
# restriction, no level window, no hand/skill flags (see PetItemContentBaseline).
$consumeKind = 'consume item'
$consumeSlot = 0

$equipmentSlots = @{
    'head' = 0; 'amulet' = 1; 'glove' = 2; 'armor' = 3; 'cloth' = 3
    'cuff' = 4; 'girdle' = 5; 'shoes' = 6; 'leggins' = 7; 'ring' = 8
    'weapon' = 10; 'shield' = 11; 'stylish' = 12
    'mounthead' = 15; 'mountarmor' = 16; 'mountsoul' = 17
    'mountornament' = 18; 'mountamulet' = 19; 'mount' = 20
}

# Requested identities, unioned across every supplied list file. Each entry may
# also carry a comma or semicolon separated list of files so the tool stays
# usable through `pwsh -File`.
$requested = New-Object System.Collections.Generic.List[int]
$seen = New-Object 'System.Collections.Generic.HashSet[int]'
$listFiles = @($ItemIdsFile | ForEach-Object { $_ -split '[,;]' } |
    ForEach-Object { $_.Trim() } | Where-Object { $_ })
foreach ($file in $listFiles) {
    if (-not (Test-Path $file)) { throw "Item id list not found: $file" }
    foreach ($line in [System.IO.File]::ReadAllLines($file)) {
        $text = ($line -split '#', 2)[0].Trim()
        if ([string]::IsNullOrWhiteSpace($text)) { continue }
        $id = [int]$text
        if ($seen.Add($id)) { $requested.Add($id) }
    }
}
if ($requested.Count -eq 0) { throw "No item ids found in $($listFiles -join ', ')" }

# Display names transcribed from the stock English client.
$displayNames = @{}
foreach ($line in [System.IO.File]::ReadAllLines($equipNamePath)) {
    if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith('//')) { continue }
    $parts = $line -split "`t", 2
    if ($parts.Count -eq 2 -and $parts[0].Trim()) {
        $key = $parts[0].Trim()
        if (-not $displayNames.ContainsKey($key)) { $displayNames[$key] = $parts[1].Trim() }
    }
}

[xml]$itemBase = Get-Content $itemBasePath -Raw
$byId = @{}
foreach ($node in $itemBase.SelectNodes('/ItemBaseAttribute//*[@ID]')) {
    $id = [int]$node.GetAttribute('ID')
    if (-not $byId.ContainsKey($id)) { $byId[$id] = $node }
}

$templates = New-Object System.Collections.Generic.List[object]
$missing = New-Object System.Collections.Generic.List[int]
foreach ($id in $requested) {
    if (-not $byId.ContainsKey($id)) { $missing.Add($id); continue }
    $node = $byId[$id]

    $attributes = [ordered]@{}
    foreach ($attribute in $node.Attributes) { $attributes[$attribute.Name] = $attribute.Value }

    $clientType = [string]$attributes['Type']
    if ($equipmentSlots.ContainsKey($clientType)) {
        $kind = $clientType
        $slot = $equipmentSlots[$clientType]
        $classIds = @()
        if (-not [string]::IsNullOrWhiteSpace($attributes['Class'])) {
            $classIds = $attributes['Class'].Split(',', [StringSplitOptions]::RemoveEmptyEntries) |
                ForEach-Object { [int16]$_.Trim() }
        }
        $playLevel = ([string]$attributes['PlayLv']) -split ',', 2
        $minLevel = if ($playLevel.Count -ge 1 -and $playLevel[0]) { [int]$playLevel[0] } else { $null }
        $maxLevel = if ($playLevel.Count -ge 2 -and $playLevel[1]) { [int]$playLevel[1] } else { $null }
        $hand = if ($attributes['Hand']) { [int16]$attributes['Hand'] } else { $null }
        $skillFlag = if ($attributes['SkillFlag']) { [int]$attributes['SkillFlag'] } else { $null }
    }
    else {
        # Everything the equipment-only generator skipped is published as the
        # repository's canonical consume item; the client's original Type is
        # preserved inside stats.
        $kind = $consumeKind
        $slot = $consumeSlot
        $classIds = @()
        $minLevel = $null
        $maxLevel = $null
        $hand = $null
        $skillFlag = $null
    }

    $displayName = $displayNames[$node.Name]
    if ([string]::IsNullOrWhiteSpace($displayName)) { $displayName = $node.Name }

    $templates.Add([pscustomobject]@{
            Id          = $id
            Kind        = $kind
            NameKey     = $node.Name
            DisplayName = $displayName
            Slot        = $slot
            ClassIds    = @($classIds)
            MinLevel    = $minLevel
            MaxLevel    = $maxLevel
            Hand        = $hand
            SkillFlag   = $skillFlag
            Texture     = [string]$attributes['Texture']
            Icon        = [string]$attributes['Icon']
            StatsJson   = ($attributes | ConvertTo-Json -Compress)
        })
}

if ($missing.Count -gt 0) {
    throw ("Item ids absent from the client catalog: " + ($missing -join ', '))
}

$templates = @($templates | Sort-Object Id)

# ------------------------------------------------------------------ C# seed
$csharp = [System.Text.StringBuilder]::new()
[void]$csharp.AppendLine('// <auto-generated />')
[void]$csharp.AppendLine('// Generated by tools/GenerateClientCatalogItemSeeds.ps1 from Godswar Origin')
[void]$csharp.AppendLine('// Localization/en_us/Settings/Sys/ItemBaseAttribute.xml and Text/EquipName.dat.')
[void]$csharp.AppendLine('namespace Godswar.Server.State;')
[void]$csharp.AppendLine()
[void]$csharp.AppendLine('/// <summary>')
[void]$csharp.AppendLine('/// Reviewed client-catalog identities the equipment-only generator skipped.')
[void]$csharp.AppendLine('/// Published as the immutable item-content family "client-catalog-v1".')
[void]$csharp.AppendLine('/// </summary>')
[void]$csharp.AppendLine('internal static class ClientCatalogItemSeeds')
[void]$csharp.AppendLine('{')
[void]$csharp.AppendLine("    public const int ShippedItemCount = $($templates.Count);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine('    public static IReadOnlyList<ItemTemplateSeed> All { get; } =')
[void]$csharp.AppendLine('    [')
foreach ($t in $templates) {
    $classIds = if ($t.ClassIds.Count -eq 0) { '[]' } else {
        'new short[] { ' + (($t.ClassIds | ForEach-Object { [int16]$_ }) -join ', ') + ' }'
    }
    $minLevel = if ($null -eq $t.MinLevel) { 'null' } else { $t.MinLevel }
    $maxLevel = if ($null -eq $t.MaxLevel) { 'null' } else { $t.MaxLevel }
    $hand = if ($null -eq $t.Hand) { 'null' } else { $t.Hand }
    $skillFlag = if ($null -eq $t.SkillFlag) { 'null' } else { $t.SkillFlag }
    [void]$csharp.AppendLine(
        '        new(' +
        "$($t.Id), " +
        "$(ConvertTo-CSharpString $t.Kind), " +
        "$(ConvertTo-CSharpString $t.NameKey), " +
        "$(ConvertTo-CSharpString $t.DisplayName), " +
        "$($t.Slot), " +
        "$classIds, " +
        "$minLevel, " +
        "$maxLevel, " +
        "$hand, " +
        "$skillFlag, " +
        "$(ConvertTo-CSharpString $t.Texture), " +
        "$(ConvertTo-CSharpString $t.Icon), " +
        "$(ConvertTo-CSharpString $t.StatsJson)),")
}
[void]$csharp.AppendLine('    ];')
[void]$csharp.AppendLine('}')

# ----------------------------------------------------------------- SQL seed
$sql = [System.Text.StringBuilder]::new()
[void]$sql.AppendLine($sqlHeader)
[void]$sql.AppendLine('INSERT INTO public.item_templates (')
[void]$sql.AppendLine('    id, kind, name_key, display_name, equipment_slot, class_ids,')
[void]$sql.AppendLine('    min_level, max_level, hand, skill_flag, texture, icon, stats)')
[void]$sql.AppendLine('VALUES')
for ($i = 0; $i -lt $templates.Count; $i++) {
    $t = $templates[$i]
    $classIds = if ($t.ClassIds.Count -eq 0) { "ARRAY[]::smallint[]" } else {
        'ARRAY[' + (($t.ClassIds | ForEach-Object { [int16]$_ }) -join ',') + ']::smallint[]'
    }
    $suffix = if ($i -eq $templates.Count - 1) { '' } else { ',' }
    [void]$sql.AppendLine(
        '    (' +
        "$($t.Id), " +
        "$(ConvertTo-SqlString $t.Kind), " +
        "$(ConvertTo-SqlString $t.NameKey), " +
        "$(ConvertTo-SqlString $t.DisplayName), " +
        "$($t.Slot), " +
        "$classIds, " +
        "$(if ($null -eq $t.MinLevel) { 'NULL' } else { $t.MinLevel }), " +
        "$(if ($null -eq $t.MaxLevel) { 'NULL' } else { $t.MaxLevel }), " +
        "$(if ($null -eq $t.Hand) { 'NULL' } else { $t.Hand }), " +
        "$(if ($null -eq $t.SkillFlag) { 'NULL' } else { $t.SkillFlag }), " +
        "$(ConvertTo-SqlString $t.Texture), " +
        "$(ConvertTo-SqlString $t.Icon), " +
        "$(ConvertTo-SqlString $t.StatsJson)::jsonb)" +
        "$suffix")
}
[void]$sql.AppendLine('ON CONFLICT (id) DO UPDATE')
[void]$sql.AppendLine('SET kind = EXCLUDED.kind,')
[void]$sql.AppendLine('    name_key = EXCLUDED.name_key,')
[void]$sql.AppendLine('    display_name = EXCLUDED.display_name,')
[void]$sql.AppendLine('    equipment_slot = EXCLUDED.equipment_slot,')
[void]$sql.AppendLine('    class_ids = EXCLUDED.class_ids,')
[void]$sql.AppendLine('    min_level = EXCLUDED.min_level,')
[void]$sql.AppendLine('    max_level = EXCLUDED.max_level,')
[void]$sql.AppendLine('    hand = EXCLUDED.hand,')
[void]$sql.AppendLine('    skill_flag = EXCLUDED.skill_flag,')
[void]$sql.AppendLine('    texture = EXCLUDED.texture,')
[void]$sql.AppendLine('    icon = EXCLUDED.icon,')
[void]$sql.AppendLine('    stats = EXCLUDED.stats;')

$seedFull = Join-Path $ServerRoot $SeedOutputPath
$sqlFull = Join-Path $ServerRoot $SqlOutputPath
New-Item -ItemType Directory -Force -Path (Split-Path $seedFull -Parent) | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $sqlFull -Parent) | Out-Null
Set-Content -Path $seedFull -Value $csharp.ToString() -Encoding UTF8
Set-Content -Path $sqlFull -Value $sql.ToString() -Encoding UTF8

Get-Item $seedFull, $sqlFull | Select-Object FullName, Length
Write-Output "Generated $($templates.Count) reviewed client-catalog item templates."
