namespace Godswar.Server.State;

internal static partial class PostgresSchemaMigrationCatalog
{
    private const string FactionCrierEvidenceSql =
        """
        CREATE TABLE public.faction_crier_daily_claims (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            account_id integer NOT NULL,
            character_id integer NOT NULL,
            realm_id integer NOT NULL,
            claim_day date NOT NULL,
            plate_item_id integer NOT NULL,
            balance_revision bigint NOT NULL,
            item_content_revision varchar(64) NOT NULL,
            command_inbox_id bigint NOT NULL,
            audit_id bigint NOT NULL,
            outbox_event_id uuid NOT NULL,
            wallet_revision bigint NOT NULL,
            inventory_revision bigint NOT NULL,
            progression_revision bigint NOT NULL,
            faction_crier_revision bigint NOT NULL,
            committed_at timestamptz NOT NULL
                DEFAULT transaction_timestamp(),
            CONSTRAINT uq_faction_crier_daily_period
                UNIQUE (character_id, realm_id, claim_day),
            CONSTRAINT uq_faction_crier_daily_inbox
                UNIQUE (command_inbox_id),
            CONSTRAINT uq_faction_crier_daily_audit UNIQUE (audit_id),
            CONSTRAINT uq_faction_crier_daily_outbox
                UNIQUE (outbox_event_id),
            CONSTRAINT fk_faction_crier_daily_account
                FOREIGN KEY (account_id)
                REFERENCES public.accounts (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_daily_character
                FOREIGN KEY (character_id, account_id)
                REFERENCES public.character_economy_baseline (
                    character_id, account_id
                ) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_daily_realm
                FOREIGN KEY (realm_id)
                REFERENCES public.server (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_daily_balance
                FOREIGN KEY (balance_revision)
                REFERENCES public.faction_crier_balance_revisions (revision)
                ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_daily_item_revision
                FOREIGN KEY (item_content_revision)
                REFERENCES public.item_template_content_revisions (revision)
                ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_daily_item
                FOREIGN KEY (item_content_revision, plate_item_id)
                REFERENCES public.item_template_content_definitions (
                    revision, id
                ) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_daily_inbox
                FOREIGN KEY (command_inbox_id)
                REFERENCES public.command_inbox (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_daily_audit
                FOREIGN KEY (audit_id)
                REFERENCES public.command_audit (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_daily_outbox
                FOREIGN KEY (outbox_event_id)
                REFERENCES public.outbox_events (event_id)
                ON DELETE RESTRICT,
            CONSTRAINT ck_faction_crier_daily_identity CHECK (
                account_id > 0 AND character_id > 0 AND realm_id > 0
            ),
            CONSTRAINT ck_faction_crier_daily_plate CHECK (
                EXTRACT(ISODOW FROM claim_day) BETWEEN 1 AND 6
                AND plate_item_id =
                    3819 + EXTRACT(ISODOW FROM claim_day)::integer
            ),
            CONSTRAINT ck_faction_crier_daily_revisions CHECK (
                wallet_revision >= 0
                AND inventory_revision > 0
                AND progression_revision >= 0
                AND faction_crier_revision > 0
            )
        );

        CREATE INDEX ix_faction_crier_daily_account_time
            ON public.faction_crier_daily_claims (
                account_id, committed_at DESC, id
            );

        CREATE TABLE public.faction_crier_weekly_reclaims (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            account_id integer NOT NULL,
            character_id integer NOT NULL,
            realm_id integer NOT NULL,
            week_start date NOT NULL,
            plate_item_id integer NOT NULL,
            gold_cost integer NOT NULL,
            balance_revision bigint NOT NULL,
            item_content_revision varchar(64) NOT NULL,
            command_inbox_id bigint NOT NULL,
            audit_id bigint NOT NULL,
            outbox_event_id uuid NOT NULL,
            wallet_revision bigint NOT NULL,
            inventory_revision bigint NOT NULL,
            progression_revision bigint NOT NULL,
            faction_crier_revision bigint NOT NULL,
            committed_at timestamptz NOT NULL
                DEFAULT transaction_timestamp(),
            CONSTRAINT uq_faction_crier_weekly_period
                UNIQUE (character_id, realm_id, week_start),
            CONSTRAINT uq_faction_crier_weekly_inbox
                UNIQUE (command_inbox_id),
            CONSTRAINT uq_faction_crier_weekly_audit UNIQUE (audit_id),
            CONSTRAINT uq_faction_crier_weekly_outbox
                UNIQUE (outbox_event_id),
            CONSTRAINT fk_faction_crier_weekly_account
                FOREIGN KEY (account_id)
                REFERENCES public.accounts (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_weekly_character
                FOREIGN KEY (character_id, account_id)
                REFERENCES public.character_economy_baseline (
                    character_id, account_id
                ) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_weekly_realm
                FOREIGN KEY (realm_id)
                REFERENCES public.server (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_weekly_balance
                FOREIGN KEY (balance_revision)
                REFERENCES public.faction_crier_balance_revisions (revision)
                ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_weekly_item_revision
                FOREIGN KEY (item_content_revision)
                REFERENCES public.item_template_content_revisions (revision)
                ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_weekly_item
                FOREIGN KEY (item_content_revision, plate_item_id)
                REFERENCES public.item_template_content_definitions (
                    revision, id
                ) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_weekly_inbox
                FOREIGN KEY (command_inbox_id)
                REFERENCES public.command_inbox (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_weekly_audit
                FOREIGN KEY (audit_id)
                REFERENCES public.command_audit (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_weekly_outbox
                FOREIGN KEY (outbox_event_id)
                REFERENCES public.outbox_events (event_id)
                ON DELETE RESTRICT,
            CONSTRAINT ck_faction_crier_weekly_identity CHECK (
                account_id > 0 AND character_id > 0 AND realm_id > 0
            ),
            CONSTRAINT ck_faction_crier_weekly_period CHECK (
                EXTRACT(ISODOW FROM week_start) = 1
                AND plate_item_id BETWEEN 3820 AND 3825
            ),
            CONSTRAINT ck_faction_crier_weekly_values CHECK (
                gold_cost BETWEEN 0 AND 2147483647
                AND wallet_revision >= 0
                AND inventory_revision > 0
                AND progression_revision >= 0
                AND faction_crier_revision > 0
            )
        );

        CREATE INDEX ix_faction_crier_weekly_account_time
            ON public.faction_crier_weekly_reclaims (
                account_id, committed_at DESC, id
            );

        CREATE TABLE public.faction_crier_exchange_settlements (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            account_id integer NOT NULL,
            character_id integer NOT NULL,
            realm_id integer NOT NULL,
            operation varchar(16) NOT NULL,
            sub_id smallint NOT NULL,
            consumed_item_ids integer[] NOT NULL,
            granted_item_id integer,
            currency_code varchar(16) NOT NULL,
            currency_cost integer NOT NULL,
            awarded_experience integer NOT NULL,
            awarded_talent_points integer NOT NULL,
            balance_revision bigint NOT NULL,
            item_content_revision varchar(64) NOT NULL,
            command_inbox_id bigint NOT NULL,
            audit_id bigint NOT NULL,
            outbox_event_id uuid NOT NULL,
            wallet_revision bigint NOT NULL,
            inventory_revision bigint NOT NULL,
            progression_revision bigint NOT NULL,
            faction_crier_revision bigint NOT NULL,
            committed_at timestamptz NOT NULL
                DEFAULT transaction_timestamp(),
            CONSTRAINT uq_faction_crier_exchange_inbox
                UNIQUE (command_inbox_id),
            CONSTRAINT uq_faction_crier_exchange_audit UNIQUE (audit_id),
            CONSTRAINT uq_faction_crier_exchange_outbox
                UNIQUE (outbox_event_id),
            CONSTRAINT fk_faction_crier_exchange_account
                FOREIGN KEY (account_id)
                REFERENCES public.accounts (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_exchange_character
                FOREIGN KEY (character_id, account_id)
                REFERENCES public.character_economy_baseline (
                    character_id, account_id
                ) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_exchange_realm
                FOREIGN KEY (realm_id)
                REFERENCES public.server (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_exchange_balance
                FOREIGN KEY (balance_revision)
                REFERENCES public.faction_crier_balance_revisions (revision)
                ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_exchange_item_revision
                FOREIGN KEY (item_content_revision)
                REFERENCES public.item_template_content_revisions (revision)
                ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_exchange_inbox
                FOREIGN KEY (command_inbox_id)
                REFERENCES public.command_inbox (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_exchange_audit
                FOREIGN KEY (audit_id)
                REFERENCES public.command_audit (id) ON DELETE RESTRICT,
            CONSTRAINT fk_faction_crier_exchange_outbox
                FOREIGN KEY (outbox_event_id)
                REFERENCES public.outbox_events (event_id)
                ON DELETE RESTRICT,
            CONSTRAINT ck_faction_crier_exchange_identity CHECK (
                account_id > 0 AND character_id > 0 AND realm_id > 0
            ),
            CONSTRAINT ck_faction_crier_exchange_operation CHECK (
                operation IN ('turn_in', 'renewal')
            ),
            CONSTRAINT ck_faction_crier_exchange_items CHECK (
                cardinality(consumed_item_ids) BETWEEN 1 AND 6
                AND consumed_item_ids <@
                    ARRAY[3820,3821,3822,3823,3824,3825]
                AND (
                    granted_item_id IS NULL
                    OR granted_item_id BETWEEN 3820 AND 3825
                )
            ),
            CONSTRAINT ck_faction_crier_exchange_currency CHECK (
                currency_code IN (
                    'none', 'silver', 'binding_gold', 'gold'
                )
                AND currency_cost BETWEEN 0 AND 2147483647
                AND (
                    (currency_code = 'none' AND currency_cost = 0)
                    OR currency_code <> 'none'
                )
            ),
            CONSTRAINT ck_faction_crier_exchange_rewards CHECK (
                awarded_experience BETWEEN 0 AND 2147483647
                AND awarded_talent_points BETWEEN 0 AND 2147483647
            ),
            CONSTRAINT ck_faction_crier_exchange_shape CHECK (
                (
                    operation = 'renewal'
                    AND sub_id BETWEEN 41 AND 46
                    AND cardinality(consumed_item_ids) = 1
                    AND granted_item_id IS NOT NULL
                    AND currency_code = 'gold'
                    AND awarded_experience = 0
                    AND awarded_talent_points = 0
                ) OR (
                    operation = 'turn_in'
                    AND (
                        sub_id BETWEEN 101 AND 106
                        OR sub_id BETWEEN 110 AND 134
                    )
                    AND granted_item_id IS NULL
                    AND cardinality(consumed_item_ids) = CASE
                        WHEN sub_id BETWEEN 101 AND 106 THEN 1
                        WHEN sub_id BETWEEN 110 AND 129 THEN 3
                        ELSE 6
                    END
                )
            ),
            CONSTRAINT ck_faction_crier_exchange_stock_items CHECK (
                (
                    operation = 'renewal'
                    AND granted_item_id = 3779 + sub_id
                    AND granted_item_id <> ALL(consumed_item_ids)
                ) OR (
                    operation = 'turn_in'
                    AND consumed_item_ids = CASE
                        WHEN sub_id BETWEEN 101 AND 106 THEN
                            ARRAY[3719 + sub_id::integer]
                        WHEN sub_id BETWEEN 110 AND 119 THEN
                            ARRAY[3820,3822,3824]
                        WHEN sub_id BETWEEN 120 AND 129 THEN
                            ARRAY[3821,3823,3825]
                        WHEN sub_id BETWEEN 130 AND 134 THEN
                            ARRAY[3820,3821,3822,3823,3824,3825]
                        ELSE ARRAY[]::integer[]
                    END
                )
            ),
            CONSTRAINT ck_faction_crier_exchange_revisions CHECK (
                wallet_revision >= 0
                AND inventory_revision > 0
                AND progression_revision >= 0
                AND faction_crier_revision > 0
            )
        );

        CREATE INDEX ix_faction_crier_exchange_character_time
            ON public.faction_crier_exchange_settlements (
                character_id, committed_at DESC, id
            );

        CREATE TRIGGER trg_faction_crier_daily_claims_immutable
        BEFORE UPDATE OR DELETE ON public.faction_crier_daily_claims
        FOR EACH ROW EXECUTE FUNCTION
            public.reject_character_economy_evidence_mutation();
        CREATE TRIGGER trg_faction_crier_daily_claims_no_truncate
        BEFORE TRUNCATE ON public.faction_crier_daily_claims
        FOR EACH STATEMENT EXECUTE FUNCTION
            public.reject_character_economy_evidence_mutation();

        CREATE TRIGGER trg_faction_crier_weekly_reclaims_immutable
        BEFORE UPDATE OR DELETE ON public.faction_crier_weekly_reclaims
        FOR EACH ROW EXECUTE FUNCTION
            public.reject_character_economy_evidence_mutation();
        CREATE TRIGGER trg_faction_crier_weekly_reclaims_no_truncate
        BEFORE TRUNCATE ON public.faction_crier_weekly_reclaims
        FOR EACH STATEMENT EXECUTE FUNCTION
            public.reject_character_economy_evidence_mutation();

        CREATE TRIGGER trg_faction_crier_exchange_settlements_immutable
        BEFORE UPDATE OR DELETE
            ON public.faction_crier_exchange_settlements
        FOR EACH ROW EXECUTE FUNCTION
            public.reject_character_economy_evidence_mutation();
        CREATE TRIGGER trg_faction_crier_exchange_settlements_no_truncate
        BEFORE TRUNCATE ON public.faction_crier_exchange_settlements
        FOR EACH STATEMENT EXECUTE FUNCTION
            public.reject_character_economy_evidence_mutation();
        """;
}
