namespace Godswar.Server.State;

// Generated by tools/generate-guild-content-migration.py from the client's
// Localization/*/Settings/Sys files. Do not edit by hand: re-run the generator
// so the server's guild content stays identical to the shipped client.
internal static partial class PostgresSchemaMigrationCatalog
{
    private static PostgresSchemaMigration CreateGuildContent() =>
        new(
            "20260916_159_guild_content",
            "Seed guild duties, levels, buildings and defaults from the client",
            """

            CREATE TABLE public.guild_duties (
                duty smallint PRIMARY KEY,
                display_name character varying(32) NOT NULL,
                rank smallint NOT NULL,
                CONSTRAINT ck_guild_duties_rank CHECK (rank >= 0)
            );

            INSERT INTO public.guild_duties (duty, display_name, rank) VALUES
                (0, '无', 0),
                (1, '见习会员', 1),
                (2, '会员', 2),
                (3, '精英', 3),
                (4, '理事', 4),
                (5, '副会长', 5),
                (6, '会长', 6);

            ALTER TABLE public.guild_members
                ADD CONSTRAINT fk_guild_members_duty
                FOREIGN KEY (duty) REFERENCES public.guild_duties(duty)
                ON DELETE RESTRICT;

            CREATE TABLE public.guild_levels (
                level integer PRIMARY KEY,
                upgrade_found bigint NOT NULL CHECK (upgrade_found >= 0),
                upgrade_bijou bigint NOT NULL CHECK (upgrade_bijou >= 0),
                CONSTRAINT ck_guild_levels_level CHECK (level BETWEEN 1 AND 12)
            );

            INSERT INTO public.guild_levels (level, upgrade_found, upgrade_bijou)
            VALUES
                (1, 0, 0),
                (2, 10000, 100),
                (3, 25000, 250),
                (4, 40000, 400),
                (5, 60000, 600),
                (6, 100000, 1000),
                (7, 160000, 1600),
                (8, 250000, 2500),
                (9, 400000, 4000),
                (10, 700000, 7000),
                (11, 1200000, 12000),
                (12, 2000000, 20000);

            CREATE TABLE public.guild_building_types (
                building_type integer PRIMARY KEY,
                name_key character varying(64) NOT NULL,
                display_name character varying(96) NOT NULL,
                maximum_level smallint NOT NULL CHECK (maximum_level BETWEEN 1 AND 12)
            );

            INSERT INTO public.guild_building_types (
                building_type, name_key, display_name, maximum_level)
            VALUES
                (1, 'Guild Footstone', 'Guild Footstone', 12),
                (2, 'Common Guild Warehouse', 'Common Guild Warehouse', 12),
                (3, 'Super Guild Warehouse', 'Super Guild Warehouse', 12),
                (4, 'Common Tent', 'Common Tent', 10),
                (5, 'Senior House', 'Senior House', 10),
                (6, 'Luxurious House', 'Luxurious House', 10),
                (10, 'Apollo', 'Apollo', 12),
                (11, 'Demeter', 'Demeter', 12),
                (12, 'Hermes', 'Hermes', 12),
                (13, 'Hephaestus', 'Hephaestus', 12),
                (14, 'Hades', 'Hades', 12),
                (15, 'Dionysus', 'Dionysus', 12),
                (16, 'Aphrodite', 'Aphrodite', 12),
                (17, 'Hestia', 'Hestia', 12),
                (18, 'Poseidon', 'Poseidon', 12),
                (19, 'Artemis', 'Artemis', 12),
                (30, 'God Altar', 'God Altar', 8);

            CREATE TABLE public.guild_building_levels (
                building_type integer NOT NULL
                    REFERENCES public.guild_building_types(building_type)
                    ON DELETE CASCADE,
                level smallint NOT NULL CHECK (level BETWEEN 1 AND 12),
                upgrade_found bigint NOT NULL CHECK (upgrade_found >= 0),
                upgrade_bijou bigint NOT NULL CHECK (upgrade_bijou >= 0),
                PRIMARY KEY (building_type, level)
            );

            INSERT INTO public.guild_building_levels (
                building_type, level, upgrade_found, upgrade_bijou)
            VALUES
                (1, 1, 0, 0),
                (1, 2, 10000, 100),
                (1, 3, 25000, 250),
                (1, 4, 40000, 400),
                (1, 5, 60000, 600),
                (1, 6, 100000, 1000),
                (1, 7, 160000, 1600),
                (1, 8, 250000, 2500),
                (1, 9, 400000, 4000),
                (1, 10, 700000, 7000),
                (1, 11, 1200000, 12000),
                (1, 12, 2000000, 20000),
                (2, 1, 10000, 100),
                (2, 2, 20000, 200),
                (2, 3, 30000, 300),
                (2, 4, 40000, 400),
                (2, 5, 60000, 600),
                (2, 6, 100000, 1000),
                (2, 7, 240000, 2400),
                (2, 8, 500000, 5000),
                (2, 9, 720000, 7200),
                (2, 10, 840000, 8400),
                (2, 11, 960000, 9600),
                (2, 12, 1200000, 12000),
                (3, 1, 10000, 1000),
                (3, 2, 180000, 1800),
                (3, 3, 360000, 3600),
                (3, 4, 540000, 7200),
                (3, 5, 720000, 10800),
                (3, 6, 900000, 14400),
                (3, 7, 1440000, 19800),
                (3, 8, 1800000, 25200),
                (3, 9, 2160000, 32400),
                (3, 10, 2520000, 39600),
                (3, 11, 2880000, 46800),
                (3, 12, 3600000, 57600),
                (4, 1, 5000, 50),
                (4, 2, 10000, 100),
                (4, 3, 15000, 150),
                (4, 4, 20000, 200),
                (4, 5, 25000, 250),
                (4, 6, 30000, 300),
                (4, 7, 35000, 350),
                (4, 8, 40000, 400),
                (4, 9, 45000, 450),
                (4, 10, 50000, 500),
                (5, 1, 20000, 200),
                (5, 2, 30000, 300),
                (5, 3, 40000, 400),
                (5, 4, 50000, 500),
                (5, 5, 60000, 600),
                (5, 6, 80000, 800),
                (5, 7, 100000, 1000),
                (5, 8, 120000, 1200),
                (5, 9, 150000, 1500),
                (5, 10, 200000, 2000),
                (6, 1, 80000, 800),
                (6, 2, 100000, 1000),
                (6, 3, 120000, 1200),
                (6, 4, 150000, 1500),
                (6, 5, 200000, 2000),
                (6, 6, 300000, 3000),
                (6, 7, 400000, 4000),
                (6, 8, 500000, 5000),
                (6, 9, 700000, 7000),
                (6, 10, 1000000, 10000),
                (10, 1, 20000, 200),
                (10, 2, 30000, 300),
                (10, 3, 60000, 600),
                (10, 4, 90000, 900),
                (10, 5, 120000, 1200),
                (10, 6, 150000, 1500),
                (10, 7, 240000, 2400),
                (10, 8, 300000, 3000),
                (10, 9, 360000, 3600),
                (10, 10, 420000, 4200),
                (10, 11, 480000, 4800),
                (10, 12, 600000, 6000),
                (11, 1, 20000, 200),
                (11, 2, 30000, 300),
                (11, 3, 60000, 600),
                (11, 4, 90000, 900),
                (11, 5, 120000, 1200),
                (11, 6, 150000, 1500),
                (11, 7, 240000, 2400),
                (11, 8, 300000, 3000),
                (11, 9, 360000, 3600),
                (11, 10, 420000, 4200),
                (11, 11, 480000, 4800),
                (11, 12, 600000, 6000),
                (12, 1, 20000, 200),
                (12, 2, 30000, 300),
                (12, 3, 60000, 600),
                (12, 4, 90000, 900),
                (12, 5, 120000, 1200),
                (12, 6, 150000, 1500),
                (12, 7, 240000, 2400),
                (12, 8, 300000, 3000),
                (12, 9, 360000, 3600),
                (12, 10, 420000, 4200),
                (12, 11, 480000, 4800),
                (12, 12, 600000, 6000),
                (13, 1, 20000, 200),
                (13, 2, 30000, 300),
                (13, 3, 60000, 600),
                (13, 4, 90000, 900),
                (13, 5, 120000, 1200),
                (13, 6, 150000, 1500),
                (13, 7, 240000, 2400),
                (13, 8, 300000, 3000),
                (13, 9, 360000, 3600),
                (13, 10, 420000, 4200),
                (13, 11, 480000, 4800),
                (13, 12, 600000, 6000),
                (14, 1, 20000, 200),
                (14, 2, 30000, 300),
                (14, 3, 60000, 600),
                (14, 4, 90000, 900),
                (14, 5, 120000, 1200),
                (14, 6, 150000, 1500),
                (14, 7, 240000, 2400),
                (14, 8, 300000, 3000),
                (14, 9, 360000, 3600),
                (14, 10, 420000, 4200),
                (14, 11, 480000, 4800),
                (14, 12, 600000, 6000),
                (15, 1, 20000, 200),
                (15, 2, 30000, 300),
                (15, 3, 60000, 600),
                (15, 4, 90000, 900),
                (15, 5, 120000, 1200),
                (15, 6, 150000, 1500),
                (15, 7, 240000, 2400),
                (15, 8, 300000, 3000),
                (15, 9, 360000, 3600),
                (15, 10, 420000, 4200),
                (15, 11, 480000, 4800),
                (15, 12, 600000, 6000),
                (16, 1, 20000, 200),
                (16, 2, 30000, 300),
                (16, 3, 60000, 600),
                (16, 4, 90000, 900),
                (16, 5, 120000, 1200),
                (16, 6, 150000, 1500),
                (16, 7, 240000, 2400),
                (16, 8, 300000, 3000),
                (16, 9, 360000, 3600),
                (16, 10, 420000, 4200),
                (16, 11, 480000, 4800),
                (16, 12, 600000, 6000),
                (17, 1, 20000, 200),
                (17, 2, 30000, 300),
                (17, 3, 60000, 600),
                (17, 4, 90000, 900),
                (17, 5, 120000, 1200),
                (17, 6, 150000, 1500),
                (17, 7, 240000, 2400),
                (17, 8, 300000, 3000),
                (17, 9, 360000, 3600),
                (17, 10, 420000, 4200),
                (17, 11, 480000, 4800),
                (17, 12, 600000, 6000),
                (18, 1, 20000, 200),
                (18, 2, 30000, 300),
                (18, 3, 60000, 600),
                (18, 4, 90000, 900),
                (18, 5, 120000, 1200),
                (18, 6, 150000, 1500),
                (18, 7, 240000, 2400),
                (18, 8, 300000, 3000),
                (18, 9, 360000, 3600),
                (18, 10, 420000, 4200),
                (18, 11, 480000, 4800),
                (18, 12, 600000, 6000),
                (19, 1, 20000, 200),
                (19, 2, 30000, 300),
                (19, 3, 60000, 600),
                (19, 4, 90000, 900),
                (19, 5, 120000, 1200),
                (19, 6, 150000, 1500),
                (19, 7, 240000, 2400),
                (19, 8, 300000, 3000),
                (19, 9, 360000, 3600),
                (19, 10, 420000, 4200),
                (19, 11, 480000, 4800),
                (19, 12, 600000, 6000),
                (30, 1, 500000, 5000),
                (30, 2, 900000, 9000),
                (30, 3, 1620000, 16200),
                (30, 4, 2700000, 27000),
                (30, 5, 3960000, 39600),
                (30, 6, 5760000, 57600),
                (30, 7, 8100000, 81000),
                (30, 8, 11160000, 111600);

            CREATE TABLE public.guild_building_consume (
                condition_level smallint PRIMARY KEY,
                contribute_point bigint NOT NULL CHECK (contribute_point >= 0),
                consume_value bigint NOT NULL CHECK (consume_value >= 0)
            );

            INSERT INTO public.guild_building_consume (
                condition_level, contribute_point, consume_value)
            VALUES
                (1, 10000, 50),
                (2, 30000, 120),
                (3, 60000, 320),
                (4, 90000, 800),
                (5, 120000, 1600),
                (6, 1000000, 4000);

            CREATE TABLE public.guild_defaults (
                setting_key character varying(64) PRIMARY KEY,
                setting_order smallint NOT NULL,
                setting_value character varying(32) NOT NULL
            );

            INSERT INTO public.guild_defaults (
                setting_key, setting_order, setting_value)
            VALUES
                ('Default_Member', 0, '100'),
                ('Default_MaxMember', 1, '10000'),
                ('Default_MaxAltar', 2, '100'),
                ('Default_Money', 3, '1000'),
                ('Default_MaxMoney', 4, '900000000'),
                ('Default_Bijou', 5, '10'),
                ('Default_MaxBijou', 6, '90000000'),
                ('Default_MaxContribute', 7, '900000'),
                ('Default_b', 8, '0'),
                ('Default_d', 9, '100000'),
                ('Default_MaxFactor', 10, '1.5');

            COMMENT ON TABLE public.guild_duties IS
                'Client duty names from Settings/Sys/Consortia_Job.ini (GBK): 0 none, 1 见习会员 ... 6 会长.';
            COMMENT ON TABLE public.guild_levels IS
                'Guild level upgrade costs from Consortia.xml ConsortiaLevelUp; the curve matches every building level.';
            COMMENT ON TABLE public.guild_building_types IS
                'The 17 guild buildings the client ships in Consortia.xml BuildInfo. Ids are the client''s own and are not contiguous.';
            COMMENT ON TABLE public.guild_building_levels IS
                'Per building level costs from Consortia.xml BuildingImpact; every building has twelve levels.';
            COMMENT ON TABLE public.guild_building_consume IS
                'Contribution points and consume value from Consortia.xml BuildingConsume.';
            COMMENT ON TABLE public.guild_defaults IS
                'Defaults and caps from Consortia.xml CorsortiaDefaultValue (the client spells it that way).';
            """);

    /// <summary>
    /// The attribute bonus each altar level grants, taken from the client's own
    /// <c>WorshipImpactType</c>/<c>WorshipImpactValue</c>.
    /// </summary>
    /// <remarks>
    /// The seed migration above keeps only the levels' upgrade prices, so the ten
    /// altars' own impact never reached the database and the offering points had
    /// nothing to be a percentage of. This adds those two columns and fills them
    /// from the same <c>BuildingImpact</c> block the prices come from.
    ///
    /// The values are the client's, exactly: altar <c>13</c> is 135 at level one and
    /// 540 at level twelve, which is the number <c>NF_L0_GH87</c>'s percentage is
    /// taken from. A separate migration rather than an edit of the seed because the
    /// seed has already been applied and its checksum recorded.
    /// </remarks>
    private static PostgresSchemaMigration CreateGuildWorshipImpact() =>
        new(
            "20260923_164_guild_worship_impact",
            "Seed each altar level's worship impact from the client",
            """

            ALTER TABLE public.guild_building_levels
                ADD COLUMN worship_impact_type smallint NOT NULL
                    DEFAULT -1
                    CONSTRAINT ck_guild_building_levels_worship_impact_type
                    CHECK (worship_impact_type BETWEEN -1 AND 20),
                ADD COLUMN worship_impact_value integer NOT NULL
                    DEFAULT 0
                    CONSTRAINT ck_guild_building_levels_worship_impact_value
                    CHECK (worship_impact_value >= 0);

            UPDATE public.guild_building_levels AS l
            SET worship_impact_type = v.impact_type,
                worship_impact_value = v.impact_value
            FROM (VALUES
                (10, 1, 1, 100),
                (10, 2, 1, 120),
                (10, 3, 1, 140),
                (10, 4, 1, 160),
                (10, 5, 1, 180),
                (10, 6, 1, 200),
                (10, 7, 1, 230),
                (10, 8, 1, 260),
                (10, 9, 1, 290),
                (10, 10, 1, 320),
                (10, 11, 1, 360),
                (10, 12, 1, 400),
                (11, 1, 2, 40),
                (11, 2, 2, 48),
                (11, 3, 2, 56),
                (11, 4, 2, 64),
                (11, 5, 2, 72),
                (11, 6, 2, 80),
                (11, 7, 2, 92),
                (11, 8, 2, 104),
                (11, 9, 2, 115),
                (11, 10, 2, 128),
                (11, 11, 2, 144),
                (11, 12, 2, 160),
                (12, 1, 0, 500),
                (12, 2, 0, 600),
                (12, 3, 0, 700),
                (12, 4, 0, 800),
                (12, 5, 0, 900),
                (12, 6, 0, 1000),
                (12, 7, 0, 1150),
                (12, 8, 0, 1300),
                (12, 9, 0, 1450),
                (12, 10, 0, 1600),
                (12, 11, 0, 1800),
                (12, 12, 0, 3000),
                (13, 1, 4, 135),
                (13, 2, 4, 162),
                (13, 3, 4, 189),
                (13, 4, 4, 216),
                (13, 5, 4, 243),
                (13, 6, 4, 270),
                (13, 7, 4, 310),
                (13, 8, 4, 351),
                (13, 9, 4, 391),
                (13, 10, 4, 432),
                (13, 11, 4, 486),
                (13, 12, 4, 540),
                (14, 1, 8, 24),
                (14, 2, 8, 28),
                (14, 3, 8, 33),
                (14, 4, 8, 38),
                (14, 5, 8, 43),
                (14, 6, 8, 48),
                (14, 7, 8, 55),
                (14, 8, 8, 62),
                (14, 9, 8, 69),
                (14, 10, 8, 76),
                (14, 11, 8, 86),
                (14, 12, 8, 96),
                (15, 1, 5, 115),
                (15, 2, 5, 138),
                (15, 3, 5, 161),
                (15, 4, 5, 184),
                (15, 5, 5, 207),
                (15, 6, 5, 230),
                (15, 7, 5, 264),
                (15, 8, 5, 299),
                (15, 9, 5, 333),
                (15, 10, 5, 368),
                (15, 11, 5, 414),
                (15, 12, 5, 460),
                (16, 1, 7, 70),
                (16, 2, 7, 84),
                (16, 3, 7, 98),
                (16, 4, 7, 112),
                (16, 5, 7, 126),
                (16, 6, 7, 140),
                (16, 7, 7, 161),
                (16, 8, 7, 182),
                (16, 9, 7, 203),
                (16, 10, 7, 224),
                (16, 11, 7, 252),
                (16, 12, 7, 280),
                (17, 1, 14, 50),
                (17, 2, 14, 60),
                (17, 3, 14, 70),
                (17, 4, 14, 80),
                (17, 5, 14, 90),
                (17, 6, 14, 100),
                (17, 7, 14, 115),
                (17, 8, 14, 130),
                (17, 9, 14, 145),
                (17, 10, 14, 160),
                (17, 11, 14, 180),
                (17, 12, 14, 200),
                (18, 1, 6, 105),
                (18, 2, 6, 126),
                (18, 3, 6, 147),
                (18, 4, 6, 168),
                (18, 5, 6, 189),
                (18, 6, 6, 210),
                (18, 7, 6, 241),
                (18, 8, 6, 273),
                (18, 9, 6, 304),
                (18, 10, 6, 336),
                (18, 11, 6, 378),
                (18, 12, 6, 420),
                (19, 1, 9, 24),
                (19, 2, 9, 28),
                (19, 3, 9, 33),
                (19, 4, 9, 38),
                (19, 5, 9, 43),
                (19, 6, 9, 48),
                (19, 7, 9, 55),
                (19, 8, 9, 62),
                (19, 9, 9, 69),
                (19, 10, 9, 76),
                (19, 11, 9, 86),
                (19, 12, 9, 96)
            ) AS v (building_type, level, impact_type, impact_value)
            WHERE l.building_type = v.building_type
              AND l.level = v.level;

            COMMENT ON COLUMN public.guild_building_levels.worship_impact_type IS
                'Client WorshipImpactType from Consortia.xml BuildingImpact: the attribute a worshipped altar level grants. -1 = this building level grants no worship bonus (only the ten altars at client ids 10-19 carry one).';
            COMMENT ON COLUMN public.guild_building_levels.worship_impact_value IS
                'Client WorshipImpactValue for this altar level: the attribute value the altar grants. The client''s GH87 grants a percentage of it from offering points (1000000 points = 150%, one step per 50000), so this is the base the percentage is taken from, not the final bonus.';
            """);
}
